translating svg-inline-loader
webpack-china/webpack.js.org pull request #1056
Opened 2021-04-17 13:24 UTC by KimYangOfCat

translated svg-inline-loader

- [x] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [x] Make sure your PR complies with the [writer's guide][2].
- [x] Review the diff carefully as sometimes this can reveal issues.
- [x] Do not abandon your Pull Request: [Stale Pull Requests][3].
- **Remove these instructions from your PR as they are for your eyes only.**

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

2021-04-17 14:16 UTC, QC-L commented
分支不对，带了冗余的东西。

2021-04-17 15:21 UTC, KimYangOfCat commented
> 分支不对，带了冗余的东西。

抱歉，对于这些冗余的东西，我也不知道怎么出来的。
我能想到的解决方法是，关闭本PR，然后删除我fork的仓库，然后重新fork，再重新修改并commit，最后重新提交PR，但这样的方法对我fork的仓库太具备破坏性。
所以，想请问您，是否有更好解决方法？感谢～

2021-04-17 15:44 UTC, jacob-lcs requested changes

2021-04-17 15:44 UTC, jacob-lcs commented on src/content/loaders/svg-inline-loader.md
> +此 Webpack loader 将 SVG 内联为模块。 如果你使用 Adobe Suite 或 Sketch 导出 SVG，将自动生成不需要的外壳。此 loader 也会为你移除它。
```suggestion
此 Webpack loader 将 SVG 内联为模块。如果你使用 Adobe Suite 或 Sketch 导出 SVG，将自动生成不需要的外壳。此 loader 也会为你移除它。
```

2021-04-17 15:44 UTC, jacob-lcs commented on src/content/loaders/svg-inline-loader.md
> +只需加载配置对象到 `module.loaders` 像下面这样。
```suggestion
只需像下面这样加载配置对象到  `module.loaders` 中。
```

2021-04-17 15:44 UTC, jacob-lcs commented on src/content/loaders/svg-inline-loader.md
> +警告: 这个 loader 你应只配置一次，通过 `module.loaders` 或者 `require('!...')` 配置。 更多细节参考 [#15](https://github.com/webpack-contrib/svg-inline-loader/issues/15)。
```suggestion
警告: 这个 loader 你应只能通过 `module.loaders` 或者 `require('!...')` 配置一次。更多细节参考 [#15](https://github.com/webpack-contrib/svg-inline-loader/issues/15)。
```

2021-04-17 15:44 UTC, jacob-lcs commented on src/content/loaders/svg-inline-loader.md
> +删除指定的标签和它的子元素，你可以指定标签通过设置 `removingTags` 查询多个。
```suggestion
删除指定的标签和它的子元素。你可以通过设置 `removingTags` 查询数组来指定标签。
```

2021-04-17 15:44 UTC, jacob-lcs commented on src/content/loaders/svg-inline-loader.md
> +警告: 您指定 `removeTags: true` 时，它才会执行。
```suggestion
警告：你指定 `removeTags: true` 时，它才会执行。
```

2021-04-17 15:44 UTC, jacob-lcs commented on src/content/loaders/svg-inline-loader.md
> +警告标签,例: ['desc', 'defs', 'style']
```suggestion
警告标签，不含：['desc', 'defs', 'style']
```

2021-04-17 15:44 UTC, jacob-lcs commented on src/content/loaders/svg-inline-loader.md
> +删除内部的 `<svg />`的属性。
```suggestion
删除 `<svg />` 内部的属性。
```

2021-04-17 15:44 UTC, jacob-lcs commented on src/content/loaders/svg-inline-loader.md
> +添加一个前缀到 svg 文件的 id，以避免碰撞。
```suggestion
添加一个前缀到 svg 文件的 id，以避免冲突。
```

2021-04-17 15:44 UTC, jacob-lcs commented on src/content/loaders/svg-inline-loader.md
> +通过 `module.loaders` 优先使用:
```suggestion
首选 `module.loaders` 用法：
```

2021-04-18 02:37 UTC, QC-L commented
具体流程在 #749，先改翻译吧

2021-04-18 07:39 UTC, KimYangOfCat commented
> 具体流程在 #749，先改翻译吧

我明白了，应该是我在翻译前没有新建翻译分支导致的这些冗余内容，感谢提示，非常抱歉翻译前没有了解清楚翻译流程。
那我尝试回滚到上一次翻译的commit，然后重新新建翻译分支，重新修改吧。但是我有一个问题，我不清楚 PR 是否能追踪新建的翻译分支的修改信息，因为在提交 PR 的时候，有选定合并 cn 分支，故我认为此 PR只能追踪目前这个 cn 分支修改的信息，不能追踪我新建分支的修改信息。那么此PR是否需要关闭？新建翻译分支修改之后再重新使用新的翻译分支提交PR？
或者我以上的分析都是错误的？冗余内容产生的原因并不是来自于此。

2021-04-20 01:33 UTC, QC-L commented
你把 PR 理解为特殊的分支，因为在合并提交时，我会压缩 PR 提交的内容（简单理解就是改了 commit 的 hash），这样你原来的翻译与合并的翻译并不会被认为是相同的提交，所以就产生了冗余。

新建分支的目的是与 cn 同步，保证你翻译时，内容与 cn 分支一致。

回到你的问题，新建个分支，提交 pr 不会影响现有，相当于新建了两个分支。

2021-04-20 16:50 UTC, closed without merging

2021-04-20 16:54 UTC, KimYangOfCat commented
@QC-L  感谢您的解答，我理解了，新修改的内容已通过新的PR提交，敬请斧正。