Translate the "Writing a Plugin" to Chinese
webpack-china/webpack.js.org pull request #1316
Opened 2021-09-22 11:32 UTC by jsbugwang

The Content of [Writing a Plugin](https://webpack.js.org/contribute/writing-a-plugin/) has updated dramatically since webpack v5, so updating the Chinese Translation is urgent.

_describe your changes..._

- [ ] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [ ] Make sure your PR complies with the [writer's guide][2].
- [ ] Review the diff carefully as sometimes this can reveal issues.
- [ ] Do not abandon your Pull Request: [Stale Pull Requests][3].
- **Remove these instructions from your PR as they are for your eyes only.**

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

2021-09-22 12:47 UTC, jacob-lcs requested changes

2021-09-22 12:47 UTC, jacob-lcs commented on src/content/contribute/writing-a-plugin.mdx
> +## 创建插件 $#创建插件$
```suggestion
## 创建插件 $#创建插件$
```

$$ 中间的内容是目录索引用的，不用翻译哈，下面的部分麻烦也看下～

2021-09-22 14:59 UTC, jsbugwang commented on src/content/contribute/writing-a-plugin.mdx
> +## 创建插件 $#创建插件$
已按规范修改。

2021-09-23 05:25 UTC, QC-L commented on src/content/contribute/writing-a-plugin.mdx
> +  - jsbugwang
翻译是额外的字段，参考已有的中文文档

2021-09-23 05:26 UTC, QC-L commented on src/content/contribute/writing-a-plugin.mdx
> +
这里多了空行，导致后面行数不一致

2021-09-23 05:26 UTC, QC-L commented on src/content/contribute/writing-a-plugin.mdx
> +  // 需要传入自定义插件构造函数的任意选项（这是自定义插件的公开API）
这里也是，和原文保持一致

2021-09-23 06:51 UTC, jsbugwang commented on src/content/contribute/writing-a-plugin.mdx
> +
把翻译人员从 contributors 挪到 translators

2021-09-23 06:52 UTC, jsbugwang commented on src/content/contribute/writing-a-plugin.mdx
> +  // 需要传入自定义插件构造函数的任意选项（这是自定义插件的公开API）
保持翻译后与原文行数一致：代码注释原文2行，翻译后也保持2行

2021-09-23 06:53 UTC, jsbugwang commented on src/content/contribute/writing-a-plugin.mdx
> +  - jsbugwang
把翻译人员从 contributors 挪到 translators

2021-09-23 15:45 UTC, QC-L commented on src/content/contribute/writing-a-plugin.mdx
> +  该类型的插件是一个接一个串行执行，前一个的返回值作为后一个的入参。插件需要考虑执行的顺序，因为后一个插件必须接受前一个插件执行的结果作为入参。第一个插件的参数为 `init` 。所以 waterfall 钩子至少要制定一个参数。这种模式用于和 `ModuleTemplate`，`ChunkTemplate` 等 webpack 模板相关的 Tapable 实例。
这里行数不对应，少了换行，并且下面多了一行。

2021-09-24 05:10 UTC, jsbugwang commented on src/content/contribute/writing-a-plugin.mdx
> +  该类型的插件是一个接一个串行执行，前一个的返回值作为后一个的入参。插件需要考虑执行的顺序，因为后一个插件必须接受前一个插件执行的结果作为入参。第一个插件的参数为 `init` 。所以 waterfall 钩子至少要制定一个参数。这种模式用于和 `ModuleTemplate`，`ChunkTemplate` 等 webpack 模板相关的 Tapable 实例。
检查不仔细，还是漏了这一处，多谢仔细评审，已修改。

2021-09-25 14:57 UTC, QC-L commented on src/content/contribute/writing-a-plugin.mdx
> +title: 编写一个插件
```suggestion
title: 自定义插件
```

2021-09-25 15:03 UTC, QC-L commented on src/content/contribute/writing-a-plugin.mdx
> +插件向第三方开发者提供了 webpack 引擎中完整的能力。使用阶段式的构建回调，开发者可以引入它们自己的行为到 webpack 构建流程中。创建插件比创建 loader 更加高级，因为你将需要理解一些 webpack 底层的内部特性来做相应的钩子，所以做好阅读一些源码的准备！
```suggestion
插件向第三方开发者提供了 webpack 引擎中完整的能力。使用阶段式的构建回调，开发者可以在 webpack 构建流程中引入自定义的行为。创建插件比创建 loader 更加高级，因为你需要理解 webpack 底层的特性来处理相应的钩子，所以请做好阅读源码的准备！
```

2021-09-26 10:40 UTC, jacob-lcs approved these changes

2021-09-27 04:10 UTC, QC-L approved these changes

2021-09-27 04:10 UTC, merged