docs(cn): translate src/content/plugins/eslint-webpack-plugin.mdx
webpack-china/webpack.js.org pull request #1325
Opened 2021-09-27 15:35 UTC by jsbugwang

翻译 eslint-webpack-plugin

2021-09-29 14:23 UTC, QC-L commented on src/content/plugins/eslint-webpack-plugin.mdx
> +用于 linting 的 `eslint` 实例的路径。如果 `eslintPath` 是类似官方 eslint 的目录（If the `eslintPath` is a folder like a official eslint），或者指定了 `formatter` 选项，那么就不需要安装 `eslint` 了。
```suggestion
If the `eslintPath` is a folder like a official eslint
```

2021-09-29 14:24 UTC, QC-L commented on src/content/plugins/eslint-webpack-plugin.mdx
> +用于 linting 的 `eslint` 实例的路径。如果 `eslintPath` 是类似官方 eslint 的目录（If the `eslintPath` is a folder like a official eslint），或者指定了 `formatter` 选项，那么就不需要安装 `eslint` 了。
没翻译

2021-10-01 01:19 UTC, jsbugwang commented on src/content/plugins/eslint-webpack-plugin.mdx
> +用于 linting 的 `eslint` 实例的路径。如果 `eslintPath` 是类似官方 eslint 的目录（If the `eslintPath` is a folder like a official eslint），或者指定了 `formatter` 选项，那么就不需要安装 `eslint` 了。
（）是留的英文原文去掉，可以去掉了。

2021-10-04 12:57 UTC, jacob-lcs requested changes

2021-10-04 12:57 UTC, jacob-lcs commented on src/content/plugins/eslint-webpack-plugin.mdx
> +  </a>
请不要更改原文格式哦～

2021-10-04 12:57 UTC, jacob-lcs commented on src/content/plugins/eslint-webpack-plugin.mdx
> +首先，需要安装 `eslint-webpack-plugin`:
```suggestion
首先，需要安装 `eslint-webpack-plugin`：
```

2021-10-04 12:57 UTC, jacob-lcs commented on src/content/plugins/eslint-webpack-plugin.mdx
> +**警告**: 在 eslint-webpack-plugin 版本 1 ，需要把选项传给已废弃的 [CLIEngine](https://eslint.org/docs/developer-guide/nodejs-api#cliengine)。
```suggestion
**警告**: 在 eslint-webpack-plugin 1.x 版本中 ，配置项会传递给已废弃的 [CLIEngine](https://eslint.org/docs/developer-guide/nodejs-api#cliengine)。
```

2021-10-04 12:57 UTC, jacob-lcs commented on src/content/plugins/eslint-webpack-plugin.mdx
>  ### Errors and Warning $#errors-and-warning$
```suggestion
### 错误以及警告 $#errors-and-warning$
```

2021-10-04 12:57 UTC, jacob-lcs commented on src/content/plugins/eslint-webpack-plugin.mdx
>  - Default: `false`
```suggestion
- 类型：`Boolean|Object`
- 默认值：`false`
```

2021-10-04 12:57 UTC, jacob-lcs commented on src/content/plugins/eslint-webpack-plugin.mdx
>  - Default: `true`
```suggestion
- 类型：Boolean`
- 默认值：`true`
```

2021-10-04 12:57 UTC, jacob-lcs commented on src/content/plugins/eslint-webpack-plugin.mdx
>  - Default: `true`
```suggestion
- 类型：`Boolean`
- 默认值：`true`
```

2021-10-04 12:57 UTC, jacob-lcs commented on src/content/plugins/eslint-webpack-plugin.mdx
>  - Default: `true`
下面的麻烦也改下哈～

2021-10-09 03:43 UTC, jsbugwang commented on src/content/plugins/eslint-webpack-plugin.mdx
> +  </a>
Git钩子自动格式化的，已修正。

2021-10-09 09:54 UTC, jacob-lcs commented on src/content/plugins/eslint-webpack-plugin.mdx
> +
```suggestion
```

2021-10-09 09:54 UTC, jacob-lcs commented on src/content/plugins/eslint-webpack-plugin.mdx
> +你可以传入 [eslint options](https://eslint.org/docs/developer-guide/nodejs-api#%e2%97%86-new-eslint-options) 参数。
```suggestion
你可以传入 [eslint 参数](https://eslint.org/docs/developer-guide/nodejs-api#%e2%97%86-new-eslint-options)。
```

2021-10-09 09:54 UTC, jacob-lcs commented on src/content/plugins/eslint-webpack-plugin.mdx
> +查阅 [eslint docs](https://eslint.org/docs/developer-guide/nodejs-api#%e2%97%86-new-eslint-options) 获取更多详情。
```suggestion
查阅 [eslint 文档](https://eslint.org/docs/developer-guide/nodejs-api#%e2%97%86-new-eslint-options) 获取更多详情。
```

2021-10-09 09:54 UTC, jacob-lcs commented on src/content/plugins/eslint-webpack-plugin.mdx
> +启用 [ESLint autofix feature](https://eslint.org/docs/developer-guide/nodejs-api#%e2%97%86-eslint-outputfixes-results)。
```suggestion
启用 [ESLint 自动修复特性](https://eslint.org/docs/developer-guide/nodejs-api#%e2%97%86-eslint-outputfixes-results)。
```

2021-10-09 09:54 UTC, jacob-lcs commented on src/content/plugins/eslint-webpack-plugin.mdx
> +发现的错误总是 emit ，设置为 `false` 禁用。
```suggestion
总是发送发现的错误 ，设置为 `false` 以禁用。
```

2021-10-09 09:54 UTC, jacob-lcs commented on src/content/plugins/eslint-webpack-plugin.mdx
> +发现的警告总是 emit ，设置为 `false` 禁用。
```suggestion
总是发送发现的警告，设置为 `false` 以禁用。
```

2021-10-09 09:54 UTC, jacob-lcs commented on src/content/plugins/eslint-webpack-plugin.mdx
> +任何警告都会导致模块构建（module build）失败，设置为 `false` 禁用。
```suggestion
当设置为 `true` 时，任何警告都会导致模块构建（module build）失败。
```

2021-10-11 12:24 UTC, jacob-lcs approved these changes

2021-10-11 12:26 UTC, merged