docs(cn): translate https://github.com/docschina/webpack.js.org/blob/…
webpack-china/webpack.js.org pull request #755
Opened 2020-06-15 14:03 UTC by Aastasia

翻译 API/Loader Interface 部分文档

2020-06-17 03:26 UTC, lcxfs1991 commented
这个怎么closed了

2020-06-17 14:50 UTC, Aastasia commented
> 这个怎么closed了
之前没添加Reviewers，找了一圈没有找到怎么添加，直接Reopen吧

2020-06-18 02:33 UTC, QC-L commented on src/content/api/loaders.md
> +module.exports = {
这里是复制多了，还是删少了...

2020-06-18 02:34 UTC, QC-L commented
认真核对下中英文，建议查看 [Files Change](https://github.com/docschina/webpack.js.org/pull/755/files)

2020-06-19 03:49 UTC, Aastasia commented on src/content/api/loaders.md
> +module.exports = {
应该是一不小心加进来的

2020-06-26 01:11 UTC, QC-L requested changes
请尽快修改

2020-07-26 03:19 UTC, lcxfs1991 commented
@Aastasia 请尽快修改

2020-09-01 05:14 UTC, dear-lizhihua commented
在翻译的时候，建议恢复 \`xxx\` 左右的 \` 符号不能去掉，这是 markdown 提供的高亮颜色

2020-09-01 09:30 UTC, dear-lizhihua requested changes

2020-09-01 09:30 UTC, hello-lizhihua commented on src/content/api/loaders.md
>  ## The Loader Context
The Loader Context 改为 loader context

2020-09-01 09:30 UTC, hello-lizhihua commented on src/content/api/loaders.md
>  In `/abc/file.js`:
In `/abc/file.js`:
在 `/abc/file.js` 中：

2020-09-01 09:30 UTC, hello-lizhihua commented on src/content/api/loaders.md
> +在我们的例子中：因为 resource.js 在这个目录中，这个属性为 /abc
严格点应该说：这个属性的值为 /abc

2020-09-01 09:30 UTC, hello-lizhihua commented on src/content/api/loaders.md
> +提取给定的 loader 选项，接受一个可选的 JSON 格式化对象作为参数
JSON schema 不需要翻译

2020-09-01 09:30 UTC, hello-lizhihua commented on src/content/api/loaders.md
>  In the example:
这行应该删除

2020-09-01 09:30 UTC, hello-lizhihua commented on src/content/api/loaders.md
> +应该生成一个 source map。因为生成 source map 可能会非常耗时，你应该确认 source map 确实有必要请求。
建议：你应该确认 source map 确实有必要请求 => 你应该确认是否实际需要 source map。

2020-09-01 09:30 UTC, hello-lizhihua commented on src/content/api/loaders.md
> +解析给定的 request 到一个模块，应用所有配置的 loader ，并且在回调函数中传入生成的 source 、sourceMap 和 模块实例（通常是 [`NormalModule`](https://github.com/webpack/webpack/blob/master/lib/NormalModule.js) 的一个实例）。如果你需要获取其他模块的源代码来生成结果的话，你可以使用
建议：解析给定的 request 到一个模块 => 将给定的 request 解析成一个模块

2020-09-01 09:30 UTC, hello-lizhihua commented on src/content/api/loaders.md
> +加入一个文件作为产生 loader 结果的依赖，使它们的任何变化可以被监听到。例如，[`sass-loader`](https://github.com/webpack-contrib/sass-loader), [`less-loader`](https://github.com/webpack-contrib/less-loader) 就使用了这个技巧，当它发现无论何时导入的css文件发生变
建议：当它发现无论何时导入的css文件发生变化时就会重新编译 => 任何时候当导入的 css 文件发生变化，都会触发重新编译。

2020-09-01 09:30 UTC, hello-lizhihua commented on src/content/api/loaders.md
> +产生一个文件。这是 webpack 特有的。
这是 webpack 特有的 => 这是 webpack 特定的函数

2020-09-01 09:30 UTC, hello-lizhihua commented on src/content/api/loaders.md
>    console.log(this.hot); // true if HMR is enabled via --hot flag or webpack configuration
这行删除

2020-09-01 09:30 UTC, hello-lizhihua commented on src/content/api/loaders.md
> -Read in which [`mode`](/configuration/mode/) webpack is running.
读取 webpack 正在运行在哪种 \[\`mode\`\](/configuration/mode/) 下。

2020-09-01 09:30 UTC, hello-lizhihua commented on src/content/api/loaders.md
> +## 过时的上下文属性
过时的上下文属性 => 废弃的 context 属性

2020-09-01 09:30 UTC, hello-lizhihua commented on src/content/api/loaders.md
> +像模块一样执行一些代码片段。 如果有需要查看本注释 [this comment](https://github.com/webpack/webpack.js.org/issues/1268#issuecomment-313513988) 替换方法。
像模块一样执行一些代码片段 => 像执行模块一样执行一些代码片段

2020-09-01 09:30 UTC, hello-lizhihua commented on src/content/api/loaders.md
> +从上一个 loader 那里传递过来的值。如果你会以模块的方式处理输入参数，建议预先读入这个变量（为了性能因素）。
建议预先读入这个变量（为了性能因素） => （为了更好的性能）建议预先读入这个变量

2020-09-01 09:30 UTC, hello-lizhihua commented on src/content/api/loaders.md
> +向下一个 loader 传值。如果你知道了作为模块执行后的结果，请在这里赋值（以元素数组的形式）。
以元素数组的形式 => 仅以元素数组的形式

2020-09-01 09:30 UTC, dear-lizhihua commented on src/content/api/loaders.md
>  ## Error Reporting
这行删除

2020-09-01 09:30 UTC, dear-lizhihua commented on src/content/api/loaders.md
> +您可以通过以下方式从加载程序内部报告错误：
加载程序 => loader

2020-09-01 09:30 UTC, dear-lizhihua commented on src/content/api/loaders.md
> +- 使用“throw”（或其他未捕获的意外异常）。加载程序运行时引发错误将导致当前模块编译失败。
加载程序 => loader
引发错误 => 抛出错误

2020-09-01 09:30 UTC, dear-lizhihua commented on src/content/api/loaders.md
> +这个模块将获取像下面的 bundle
此模块会被打包为如下：

2020-09-01 09:30 UTC, dear-lizhihua commented on src/content/api/loaders.md
> +如下所示，不仅有错误消息，还提供了有关所涉及的加载程序和模块的详细信息：
加载程序 => loader

2020-09-01 09:30 UTC, dear-lizhihua commented on src/content/api/loaders.md
> +T> 所有的报错和警告信息将被记录到 state 当中。详情请查看[Stats Data](/api/stats/#errors-and-warnngs)。
stats 拼写错误

2020-09-01 09:30 UTC, dear-lizhihua commented on src/content/api/loaders.md
> +在webpack v4中引入了一种新的内联请求语法。前缀为“<match resource>！=!`将为此请求设置“matchResource”。
request 不翻译

2020-09-01 09:30 UTC, dear-lizhihua commented on src/content/api/loaders.md
> +在webpack v4中引入了一种新的内联请求语法。前缀为“<match resource>！=!`将为此请求设置“matchResource”。
\`\<match-resource\>!=!\` 注意符号。
这部分好像都是机翻的，注意下格式，可能会影响编译

2020-09-01 09:30 UTC, dear-lizhihua commented on src/content/api/loaders.md
> +内联请求语法仅用于加载程序生成的代码。
加载程序 => loader

2020-09-01 09:30 UTC, dear-lizhihua commented on src/content/api/loaders.md
> +不遵循此建议将使您的代码不遵循 webpack 标准和规范。
不遵循此建议将使您的代码不遵循 webpack 标准和规范 => 不遵循此建议将使你的代码成为 webpack 特定代码和不符合规范

2020-09-01 09:30 UTC, dear-lizhihua commented on src/content/api/loaders.md
> +加载程序可以将文件转换为以下文件，并使用“matchResource”应用用户指定的CSS处理规则：
加载程序 => loader

2020-09-01 09:30 UTC, dear-lizhihua commented on src/content/api/loaders.md
> +自webpack 4.37发布以来，日志API就可用了。当 [`stats configuration`](/configuration/stats/#statslogging) 或者 [`infrastructure logging`](/configuration/other-options/#infrastructurelogging) 开启 logging 时，加载程序可以记录消息，这些
加载程序 => loader

2020-09-01 09:30 UTC, dear-lizhihua commented on src/content/api/loaders.md
> +- Loaders 最好使用 this.getLogger() 用于日志记录，这是指向 compilation.getLogger() 具有加载程序路径和已处理的文件。这种日志记录被存储到Stats中并相应地格式化。它可以被webpack用户过滤和导出。
加载程序 => loader

2020-09-01 09:30 UTC, dear-lizhihua commented on src/content/api/loaders.md
> +- Loaders 可以使用 this.getLogger("name") 获取具有子名称的独立记录器。仍会添加加载程序路径和已处理的文件。
加载程序 => loader

2020-09-01 09:30 UTC, dear-lizhihua commented on src/content/api/loaders.md
> +- Loaders 可以使用 this.getLogger("name") 获取具有子名称的独立记录器。仍会添加加载程序路径和已处理的文件。
记录器 => logger

2020-09-01 09:30 UTC, dear-lizhihua commented on src/content/api/loaders.md
> +- Loaders 可以使用特殊的回退逻辑来检测日志支持 this.getLogger() ? this.getLogger() : console。 在使用不支持 getLogger 方法的旧webpack版本时提供回退选项。
提供回退选项 => 提供回退方法

2021-02-03 12:47 UTC, closed without merging