docs(cn): translate src/content/configuration/dev-server.md
webpack-china/webpack.js.org pull request #773
Opened 2020-06-20 08:40 UTC by jerexyz

@QC-L
@dear-lizhihua
@lcxfs1991
@yuqingc

2020-06-24 02:22 UTC, QC-L commented on src/content/configuration/dev-server.md
> +T> 与[webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware) 兼容的配置项后面 🔑 标记。
```suggestion
T> 与 [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware) 兼容的配置项后面 🔑 标记。
```

2020-06-24 02:23 UTC, QC-L commented on src/content/configuration/dev-server.md
> +通过[webpack-dev-server]（https://github.com/webpack/webpack-dev-server）的这些配置，能够以多种方式改变其行为。这是一个简单的示例，利用`gzips`压缩`dist /`目录当中的所有内容并提供一个本地服务(serve)：
```suggestion
通过 [webpack-dev-server]（https://github.com/webpack/webpack-dev-server）的这些配置，能够以多种方式改变其行为。这是一个简单的示例，利用 `gzips` 压缩 `dist/` 目录当中的所有内容并提供一个本地服务(serve)：
```

2020-06-24 02:23 UTC, QC-L commented on src/content/configuration/dev-server.md
> +通过[webpack-dev-server]（https://github.com/webpack/webpack-dev-server）的这些配置，能够以多种方式改变其行为。这是一个简单的示例，利用`gzips`压缩`dist /`目录当中的所有内容并提供一个本地服务(serve)：
copy 翻译内容时，请注意格式

2020-06-24 02:24 UTC, QC-L requested changes
中英文间的空格，请全局修改下，如有问题请参考中文排版指南

2020-06-30 02:47 UTC, jerexyz commented
> 中英文间的空格，请全局修改下，如有问题请参考中文排版指南

已处理

2020-06-30 06:02 UTC, QC-L commented on src/content/configuration/dev-server.md
> +当您使用 _inline mode_ 时， DevTools 会向您显示信息， 例如： before reloading, before an error 或者当 [热加载](/concepts/hot-module-replacement/) 被开启时。
before reloading, before an error 没翻译

2020-06-30 06:02 UTC, QC-L commented on src/content/configuration/dev-server.md
> +提供了一个在`devServer`内部的所有中间件执行之前的自定义执行函数。
```suggestion
提供了一个在 `devServer` 内部的
所有中间件执行之前的自定义执行函数。
```

2020-06-30 06:03 UTC, QC-L commented on src/content/configuration/dev-server.md
> +提供了一个在`devServer`内部的所有中间件执行之前的自定义执行函数。
原文三行，你应该对应

2020-06-30 06:03 UTC, QC-L commented on src/content/configuration/dev-server.md
> +默认情况下，开发服务器将通过HTTP提供服务。 可以选择使用HTTPS通过HTTP/2提供服务：
```suggestion
默认情况下，开发服务器将通过HTTP提供服务。可以选择使用HTTPS通过HTTP/2提供服务：
```

2020-06-30 06:03 UTC, QC-L commented on src/content/configuration/dev-server.md
> +使用 [spdy](https://www.npmjs.com/package/spdy) 提供HTTP/2服务。 对于 Node 10.0.0 及更高版本，此选项将被忽略，因为 spdy 在这些版本中已被破坏。 一旦 [Express](https://expressjs.com/) 支持，开发服务器将迁移到Node内置的HTTP/2。
```suggestion
使用 [spdy](https://www.npmjs.com/package/spdy) 提供HTTP/2服务。对于 Node 10.0.0 及更高版本，此选项将被忽略，因为 spdy 在这些版本中已被破坏。一旦 [Express](https://expressjs.com/) 支持，开发服务器将迁移到Node内置的HTTP/2。
```

2020-06-30 06:04 UTC, QC-L commented on src/content/configuration/dev-server.md
> +如果在[`contentBase`](#devservercontentbase)中设置了多个静态文件夹，请提供一个字符串数组。
```suggestion
如果在 [`contentBase`](#devservercontentbase) 中设置了多个静态文件夹，请提供一个字符串数组。
```

2020-06-30 06:20 UTC, QC-L commented on src/content/configuration/dev-server.md
> +通过 [webpack-dev-server]（https://github.com/webpack/webpack-dev-server）的这些配置，能够以多种方式改变其行为。这是一个简单的示例，利用 `gzips` 压缩 `dist/` 目录当中的所有内容并提供一个本地服务(serve)：
```suggestion
通过 [webpack-dev-server](https://github.com/webpack/webpack-dev-server) 的这些配置，能够以多种方式改变其行为。这是一个简单的示例，利用 `gzips` 压缩 `dist/` 目录当中的所有内容并提供一个本地服务(serve)：
```

2020-06-30 06:21 UTC, QC-L commented on src/content/configuration/dev-server.md
> +如果您通过 Node.js API 使用 dev-server ，则`devServer`中的配置选项将被忽略。但可以将配置选项作为第二个参数传入：`new WebpackDevServer（compiler，{...}）`。 [参见此处](https://github.com/webpack/webpack-dev-server/tree/master/examples/api/simple)
```suggestion
如果您通过 Node.js API 使用 dev-server，则 `devServer` 中的配置选项将被忽略。但可以将配置选项作为第二个参数传入：`new WebpackDevServer(compiler，{...})`。[参见此处](https://github.com/webpack/webpack-dev-server/tree/master/examples/api/simple)展示了如何通过 Node.js API 使用 webpack-dev-server。
```

2020-06-30 06:21 UTC, QC-L commented on src/content/configuration/dev-server.md
> +W> 使用`WebpackDevServer`时，不能使用第二个`compiler`参数（一个回调）。
```suggestion
W> 使用 `WebpackDevServer` 时，不能使用第二个 `compiler` 参数（一个回调）。
```

2020-06-30 06:21 UTC, QC-L commented on src/content/configuration/dev-server.md
> +W> 请注意，当[导出多个配置对象](/configuration/configuration-types/#exporting-multiple-configurations)时，只会使用`devServer`的第一个配置选项，并将其应用于所有的配置当中。
```suggestion
W> 请注意，当[导出多个配置对象](/configuration/configuration-types/#exporting-multiple-configurations)时，只会使用 `devServer` 的第一个配置选项，并将其应用于所有的配置当中。
```

2020-06-30 06:22 UTC, QC-L commented on src/content/configuration/dev-server.md
> +T> 如果您碰到了问题，请将路由导航至 `/webpack-dev-server` 将会为您展示服务文件的位置。 例如： `http://localhost:9000/webpack-dev-server`。
```suggestion
T> 如果您碰到了问题，请将路由导航至 `/webpack-dev-server` 将会为您展示服务文件的位置。例如： `http://localhost:9000/webpack-dev-server`。
```

2020-06-30 06:23 UTC, QC-L commented on src/content/configuration/dev-server.md
> +T> 如果您需要要手动重新编译`bundle`，将路由导航至`/invalidate`使当前编译的`bundle`无效，并通过`webpack-dev-middleware`为您重新编译。 根据您的配置，URL可能看起来像`http://localhost:9000/invalidate`。
```suggestion
T> 如果您需要要手动重新编译 `bundle`，将路由导航至 `/invalidate` 使当前编译的 `bundle` 无效，并通过 [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware#invalidate) 为您重新编译。根据您的配置，URL 可能看起来像`http://localhost:9000/invalidate`。
```

2020-06-30 06:25 UTC, QC-L commented on src/content/configuration/dev-server.md
> +T> 当启动本地服务的时候HTML模板是必须提供的，通常是`index.html`。确保将脚本引用添加到HTML中，webpack-dev-server 不会自动注入它们。
```suggestion
T> 当启动本地服务的时候 HTML 模板是必须提供的，通常是 `index.html`。确保将脚本引用添加到 HTML 中，webpack-dev-server 不会自动注入它们。
```

2020-06-30 06:27 UTC, QC-L commented on src/content/configuration/dev-server.md
> +提供在`devServer`内部的所有中间件执行完成之后的自定义中间件。
```suggestion
提供自定义中间件，当 `devServer` 服务器内部的
所有中间件执行完成之后执行
```

2020-06-30 06:29 UTC, QC-L commented on src/content/configuration/dev-server.md
> +模仿`Django`的`ALLOWED_HOSTS`，以`.`开头的值可用作子域通配符。 `.host.com`将与`host.com`，`www.host.com`和`host.com`的任何其他子域匹配。
```suggestion
模仿 django 中的`ALLOWED_HOSTS`，以 `.` 开头的值可用作子域通配符。`.host.com` 会与 `host.com`，`www.host.com` 以及 `host.com` 等其他任何其他子域匹配。
```

2020-06-30 06:29 UTC, QC-L commented on src/content/configuration/dev-server.md
> +要将这个选项与 CLI 一起使用，请将`--allowed-hosts`的转换为用逗号分割的字符串并传入。
```suggestion
要将这个选项与 CLI 一起使用，请将 `--allowed-hosts` 的转换为用逗号分割的字符串并传入。
```

2020-06-30 06:29 UTC, QC-L commented on src/content/configuration/dev-server.md
> +`devServer.clientLogLevel` 可能太冗余，您可以通过将其设置为`'silent'`来关闭日志。
```suggestion
`devServer.clientLogLevel` 可能太冗余，您可以通过将其设置为 `'silent'` 来关闭日志。
```

2020-06-30 06:30 UTC, QC-L commented on src/content/configuration/dev-server.md
> +告诉服务器从何处提供内容。 仅当您要提供静态文件时才需要这样做。 [`devServer.publicPath`](#devserverpublicpath-) 将用于确定应从何处提供捆绑软件，并具有优先权。
```suggestion
告诉服务器从何处提供内容。 仅当您要提供静态文件时才需要这样做。[`devServer.publicPath`](#devserverpublicpath-) 将用于确定应从何处提供捆绑软件，并具有优先权。
```

2020-06-30 06:32 UTC, QC-L commented on src/content/configuration/dev-server.md
> +此选项使您可以减少[懒惰模式](#devserverlazy-)中的编译。
```suggestion
此选项可以减少在 [lazy 模式](#devserverlazy-)中的编译操作。
```

2020-06-30 06:33 UTC, QC-L commented on src/content/configuration/dev-server.md
> +此选项使您可以减少[懒惰模式](#devserverlazy-)中的编译。
文档不要用 您。
请使用你，或者不使用代替

2020-06-30 06:34 UTC, QC-L commented on src/content/configuration/dev-server.md
> +默认情况下，在[懒惰模式](#devserverlazy-)中，每个请求都将导致一个新的编译。 使用`filename`，仅当请求某个文件时才可以编译。
```suggestion
默认情况下，在 [lazy 模式](#devserverlazy-)中，每个请求都触发新的编译。使用 `filename` 仅当请求某个文件时才可执行编译。
```

2020-06-30 06:34 UTC, QC-L commented on src/content/configuration/dev-server.md
> +如果[`output.filename`](/configuration/output/#outputfilename)设置为`'bundle.js'`，则使用`devServer.filename`如下：
```suggestion
如果 [`output.filename`](/configuration/output/#outputfilename) 设置为`'bundle.js'`，则使用 `devServer.filename` 如下：
```

2020-06-30 06:35 UTC, QC-L commented on src/content/configuration/dev-server.md
> +T> `filename` 不会生效，当不实用 [懒惰模式](#devserverlazy-)时.
```suggestion
T> 当不使用 [lazy 模式](#devserverlazy-)时，`filename` 不会生效.
```

2020-06-30 06:35 UTC, QC-L commented on src/content/configuration/dev-server.md
> +T> `filename` 不会生效，当不实用 [懒惰模式](#devserverlazy-)时.
语序调整下

2020-06-30 06:35 UTC, QC-L commented on src/content/configuration/dev-server.md
> +79/5000
```suggestion
```

2020-06-30 06:35 UTC, QC-L commented on src/content/configuration/dev-server.md
> +79/5000
这是笔误？

2020-06-30 06:36 UTC, QC-L commented on src/content/configuration/dev-server.md
> +指定要使用的 host 。如果您希望服务器可从外部访问，请按以下方式指定它：
```suggestion
指定要使用的 host。如果您希望服务器可从外部访问，请按以下方式指定它：
```

2020-06-30 06:37 UTC, QC-L commented on src/content/configuration/dev-server.md
> +T> 请注意，要完全启用 HMR ，需要 [`webpack.HotModuleReplacementPlugin`](/plugins/hot-module-replacement-plugin/)。 如果使用 --hot 选项启动 `webpack` 或 `webpack-dev-server` ，该插件将自动添加，因此您可能不需要将其添加到 `webpack.config.js` 中。 有
```suggestion
T> 请注意，要完全启用 HMR ，需要 [`webpack.HotModuleReplacementPlugin`](/plugins/hot-module-replacement-plugin/)。如果使用 --hot 选项启动 `webpack` 或 `webpack-dev-server`，该插件将自动添加，因此你可能不需要将其添加到 `webpack.config.js` 中。有关更多信息，请参见 [HMR 概览章节](/concepts/hot-module-replacement/)。
```

2020-06-30 06:39 UTC, QC-L commented on src/content/configuration/dev-server.md
> +通过上述设置，将使用自签名证书，但是您可以提供自己的证书：
```suggestion
根据上述配置，将使用自签名证书，但是你也可以提供自己的证书：
```

2020-06-30 06:39 UTC, QC-L commented on src/content/configuration/dev-server.md
> +输出 cli 信息。 默认情况下启用。
```suggestion
输出 cli 信息。默认情况下启用。
```

2020-06-30 06:43 UTC, QC-L commented on src/content/configuration/dev-server.md
> +告诉 `devServer` 注入一个客户端。 将 `devServer.injectClient` 设置为 `true` 将导致总是注入客户端。 可以提供有条件注入的功能：
```suggestion
向 `devServer` 注入一个客户端。设置 `devServer.injectClient` 值为 `true` 时，会向服务注入客户端。也可以设置条件注入函数：
```

2020-06-30 06:44 UTC, QC-L commented on src/content/configuration/dev-server.md
> +告诉 `devServer` 注入热模块替换。 将 `devServer.injectHot` 设置为  `true`将导致始终注入。 可以提供有条件注入的功能：
```suggestion
告诉 `devServer` 注入热模块替换。设置 `devServer.injectHot` 值为 `true` 时，会始终注入。也可以设置条件注入函数：
```

2020-06-30 06:45 UTC, QC-L commented on src/content/configuration/dev-server.md
> +W> 确保 [`devServer.hot`](#devserverhot) 设置为 `true`，因为`devServer.injectHot` 仅适用于HMR。
```suggestion
W> 使用前请确保 [`devServer.hot`](#devserverhot) 的值设置为 `true`，因为 `devServer.injectHot` 仅适用于 HMR。
```

2020-06-30 06:45 UTC, QC-L commented on src/content/configuration/dev-server.md
> +在开发服务器的两种不同模式之间切换。 默认情况下，应用程序将启用 __inline模式__。 这意味着将在您的捆绑软件中插入脚本以进行实时重新加载，并且构建消息将出现在浏览器控制台中。
```suggestion
在开发服务器的两种不同模式之间切换。默认情况下，应用程序将启用 __inline模式__。这意味着将在 bundle 中插入脚本以进行实时重新加载，并且构建消息将出现在浏览器控制台中。
```

2020-06-30 06:47 UTC, QC-L commented
翻译的质量有点差，你翻译完没有通读吧？建议翻译完毕后，通篇读一遍。你自己就能找到问题所在~

2020-06-30 06:51 UTC, QC-L requested changes
你通篇阅读一下，再修改下。修改完我在看。

注意：不要用您

2020-07-06 14:53 UTC, QC-L commented on src/content/configuration/dev-server.md
> +T> 如果您碰到了问题，请将路由导航至 `/webpack-dev-server` 将会为您展示服务文件的位置。例如： `http://localhost:9000/webpack-dev-server`。
```suggestion
T> 如果你碰到了问题，请将路由导航至 `/webpack-dev-server` 将会为你展示服务文件的位置。例如： `http://localhost:9000/webpack-dev-server`。
```

2020-07-06 14:53 UTC, QC-L commented on src/content/configuration/dev-server.md
> +T> 如果您需要要手动重新编译 `bundle`，将路由导航至 `/invalidate` 使当前编译的 `bundle` 无效，并通过 [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware#invalidate) 为您重新编译。根据您的配置，URL 可能看起来像`http://localhost:9
```suggestion
T> 如果你需要要手动重新编译 `bundle`，将路由导航至 `/invalidate` 使当前编译的 `bundle` 无效，并通过 [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware#invalidate) 为你重新编译。根据你的配置，URL 可能看起来像 `http://localhost:9000/invalidate`。
```

2020-07-06 14:54 UTC, QC-L commented on src/content/configuration/dev-server.md
> +如果您通过 Node.js API 使用 dev-server，则 `devServer` 中的配置选项将被忽略。但可以将配置选项作为第二个参数传入：`new WebpackDevServer(compiler，{...})`。[参见此处](https://github.com/webpack/webpack-dev-server/tree/master/examples/api/simple)
```suggestion
如果你通过 Node.js API 使用 dev-server，则 `devServer` 中的配置选项将被忽略。但可以将配置选项作为第二个参数传入：`new WebpackDevServer(compiler，{...})`。[参见此处](https://github.com/webpack/webpack-dev-server/tree/master/examples/api/simple)展示了如何通过 Node.js API 使用 webpack-dev-server。
```

2020-07-06 14:56 UTC, QC-L commented on src/content/configuration/dev-server.md
> +`devServer.clientLogLevel` 可能太冗余，您可以通过将其设置为 `'silent'` 来关闭日志。
```suggestion
`devServer.clientLogLevel` 可能会导致日志过于冗余，你可以通过将其设置为 `'silent'` 来关闭日志。
```

2020-07-06 15:04 UTC, QC-L commented on src/content/configuration/dev-server.md
> +告诉服务器从何处提供内容。 仅当您要提供静态文件时才需要这样做。[`devServer.publicPath`](#devserverpublicpath-) 将用于确定应从何处提供捆绑软件，并具有优先权。
```suggestion
告诉服务器从哪个路径提供内容。仅在需要提供静态文件时才进行配置。[`devServer.publicPath`](#devserverpublicpath-) 将用于确定 bundle 的来源，并具有优先级高于 contentBase。
```

2020-07-06 15:05 UTC, QC-L commented on src/content/configuration/dev-server.md
> +告诉服务器从哪个路径提供内容。仅在需要提供静态文件时才进行配置。[`devServer.publicPath`](#devserverpublicpath-) 将用于确定 bundle 的来源，并具有优先级高于 contentBase。
```suggestion
告诉服务器内容的来源。仅在需要提供静态文件时才进行配置。[`devServer.publicPath`](#devserverpublicpath-) 将用于确定 bundle 的来源，并具有优先级高于 contentBase。
```

2020-07-06 15:05 UTC, QC-L commented on src/content/configuration/dev-server.md
> +指定要使用的 host。如果您希望服务器可从外部访问，请按以下方式指定它：
```suggestion
指定要使用的 host。如果你希望服务器可从外部访问，请按以下方式进行配置：
```

2020-07-06 15:12 UTC, QC-L commented on src/content/configuration/dev-server.md
> +如果想使用[`contentBasePublicPath`](#devservercontentbasepublicpath)在多个URL上提供静态内容，也可以从多个目录提供服务：
```suggestion
如果想使用 [`contentBasePublicPath`](#devservercontentbasepublicpath) 在多个 URL 上提供静态内容，也可以从多个目录提供服务：
```

2020-07-06 15:12 UTC, QC-L commented on src/content/configuration/dev-server.md
> +告诉服务器使用哪个URL服务 `devServer.contentBase` 静态内容。 如果有一个文件 `assets/manifest.json` ，它将在 `/serve-content-base-at-this-url/manifest.json` 中提供。
```suggestion
告诉服务器使用哪个 URL 服务 `devServer.contentBase` 静态内容。如果有一个文件 `assets/manifest.json` ，它将在 `/serve-content-base-at-this-url/manifest.json` 中提供。
```

2020-07-09 02:01 UTC, QC-L commented on src/content/configuration/dev-server.md
> +开启/关闭 命令行颜色显示。
```suggestion
开启/关闭命令行颜色显示。
```

2020-07-09 02:16 UTC, QC-L approved these changes

2020-07-09 02:18 UTC, merged