docs(cn): translate src/content/configuration/mode.md
webpack-china/webpack.js.org pull request #776
Opened 2020-06-21 16:35 UTC by navigatorOpera

2020-06-22 01:33 UTC, QC-L commented
你这标题是不是错了...

2020-06-22 01:34 UTC, QC-L commented on src/content/configuration/output.md
> +      root: "Root Comment",
不要修改原文的符号...你本地有 Lint 嘛？

2020-06-22 01:40 UTC, QC-L requested changes

2020-06-22 01:40 UTC, QC-L commented on src/content/configuration/output.md
> +**webpack.config.js**
这个也是，不要改变原文的符号

2020-06-22 01:40 UTC, QC-L commented on src/content/configuration/output.md
> +**webpack.config.js**
同

2020-06-22 01:40 UTC, QC-L commented on src/content/configuration/output.md
> +| ------------------------ | -------------------------------------------------------------------------- |
这里也是，不要自己添油加醋

2020-06-22 01:40 UTC, QC-L commented on src/content/configuration/output.md
> +| 模板                     | 描述                                                                       |
同

2020-06-22 01:40 UTC, QC-L commented on src/content/configuration/output.md
> +    devtoolModuleFilenameTemplate: (info) => {
我严重怀疑你格式化了....

2020-06-22 02:04 UTC, navigatorOpera commented on src/content/configuration/output.md
> +**webpack.config.js**
这里v4的翻译加粗是 **, 我保持一致就改了符号了，不好意思，我调整一下

2020-06-22 02:07 UTC, navigatorOpera commented on src/content/configuration/output.md
> +      root: "Root Comment",
本地有lint，不过我的格式化插件在保存时生效了，导致加了不必要的符号，我调整下

2020-06-22 02:09 UTC, navigatorOpera commented on src/content/configuration/output.md
> +| ------------------------ | -------------------------------------------------------------------------- |
这个是v4 copy过来的，存在什么问题么？

2020-06-22 12:42 UTC, navigatorOpera commented
您好，我修复了相关问题，已经提交，是否需要重新提交PR，添麻烦了。

2020-06-23 01:27 UTC, QC-L commented on src/content/configuration/output.md
> +| ------------------------ | -------------------------------------------------------------------------- |
copy 讲究的是，保证原文不变，然后基础上翻译。现在这里修改了原文，以及空格

2020-06-23 01:28 UTC, QC-L commented on src/content/configuration/output.md
> +| ------------------------ | -------------------------------------------------------------------------- |
说白了，还是格式化了。

2020-06-23 01:28 UTC, QC-L commented on src/content/configuration/output.md
> +Configure which module or modules will be exposed via the `libraryTarget`. It is `undefined` by default, same behaviour will be applied if you set `libraryTarget` to an empty string e.g. `''` it will
这里是什么情况？

2020-06-23 01:45 UTC, navigatorOpera commented on src/content/configuration/output.md
> +| ------------------------ | -------------------------------------------------------------------------- |
好的，我调整下

2020-06-23 03:59 UTC, navigatorOpera commented on src/content/configuration/output.md
> +Configure which module or modules will be exposed via the `libraryTarget`. It is `undefined` by default, same behaviour will be applied if you set `libraryTarget` to an empty string e.g. `''` it will
这个也是v4 copy过来的，我没有仔细检查其中差异，我再调整一下

2020-06-23 05:33 UTC, navigatorOpera commented
您好，相关问题已经修复，包括英文单词不一致、表格格式化、末尾逗号问题。

2020-06-24 01:46 UTC, QC-L requested changes

2020-06-24 01:46 UTC, QC-L commented on src/content/configuration/output.md
>  `output.uniqueName` will be used to generate unique globals for:
这行没翻译，然后多删了一个空行

2020-06-24 02:04 UTC, QC-L commented on src/content/configuration/output.md
> +
这里多了空行

2020-06-24 02:09 UTC, QC-L commented on src/content/configuration/output.md
> +可以使用以下替换模板字符串（通过 webpack 内部的[`TemplatedPathPlugin`][`templatedpathplugin`](https://github.com/webpack/webpack/blob/master/lib/TemplatedPathPlugin.js)）：
```suggestion
可以使用以下替换模板字符串（通过 webpack 内部的 [`TemplatedPathPlugin`](https://github.com/webpack/webpack/blob/master/lib/TemplatedPathPlugin.js)）：
```

2020-06-24 02:10 UTC, QC-L commented on src/content/configuration/output.md
> +可以使用以下替换模板字符串（通过 webpack 内部的[`TemplatedPathPlugin`][`templatedpathplugin`](https://github.com/webpack/webpack/blob/master/lib/TemplatedPathPlugin.js)）：
多删了内容吧？

2020-06-24 02:11 UTC, QC-L commented on src/content/configuration/output.md
> +确保 hash 函数有可访问的 `update` and `digest` 方法。
```suggestion
确保 hash 函数有可访问的 `update` 和 `digest` 方法。
```

2020-06-24 02:11 UTC, QC-L commented on src/content/configuration/output.md
> +`string: '[hash].hot-update.json'` `function`
```suggestion
`string = '[hash].hot-update.json'` `function`
```

2020-06-24 02:12 UTC, QC-L commented on src/content/configuration/output.md
> +`string: '[hash].hot-update.json'` `function`
这里怎么改了？

2020-06-24 02:13 UTC, QC-L commented on src/content/configuration/output.md
> +// 在一个单独的 script……
```suggestion
// 在一个单独的 script...
```

2020-06-24 02:13 UTC, QC-L commented on src/content/configuration/output.md
> +// 在一个单独的 script……
```suggestion
// 在一个单独的 script...
```

2020-06-24 02:13 UTC, QC-L commented on src/content/configuration/output.md
> +所以，使用以下配置……
```suggestion
所以，使用以下配置...
```

2020-06-24 02:14 UTC, QC-L commented on src/content/configuration/output.md
>  `libraryTarget: 'amd-require'` - This packages your output with an immediately-executed AMD `require(dependencies, factory)` wrapper.
这里也没有翻译

2020-06-30 05:54 UTC, QC-L approved these changes

2020-06-30 05:56 UTC, QC-L approved these changes

2020-06-30 05:56 UTC, merged