Feature/diff mia
webpack-china/webpack.js.org pull request #781
Opened 2020-06-24 03:40 UTC by miazhuce

_describe your changes..._
从 v1 升级到 v2 或 v3 @dear-lizhihua
- [ ] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [ ] Make sure your PR complies with the [writer's guide][2].
- [ ] Review the diff carefully as sometimes this can reveal issues.
- [ ] Do not abandon your Pull Request: [Stale Pull Requests][3].
- __Remove these instructions from your PR as they are for your eyes only.__

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

2020-06-25 05:12 UTC, lcxfs1991 commented
@miazhuce 你好，麻烦将丢掉的格式都补齐哈。尤其是丢掉的 - 符号

2020-06-25 06:02 UTC, lcxfs1991 requested changes

2020-06-25 06:02 UTC, lcxfs1991 commented on src/content/migrate/3.md
> +T> 注意：webpack 从 1 到 2 的变化，比从 2 到 3 要少很多，所以版本迁移起来难度应该不大。如果你遇到了问题，请查看 [更新日志](https://github.com/webpack/webpack/releases) 以了解更多细节。
请保证中英文的行数都保持一致

2020-06-25 06:02 UTC, lcxfs1991 commented on src/content/migrate/3.md
> +旧的 loader 配置被更强大的 rules 系统取代，后者允许配置 loader 以及其他更多选项。 为了兼容旧版，`module.loaders` 语法仍然有效，旧的属性名依然可以被解析。 新的命名约定更易于理解，并且是升级配置使用 `module.rules` 的好理由。
行数请保持一致了

2020-06-25 06:02 UTC, lcxfs1991 commented on src/content/migrate/3.md
> +好问题。严格来说，有两种办法，都可以用来配置 webpack 的 loader 。典型的 `options` 被称为 `query`，是一个可以被添加到 loader 名之后的字符串。它比较像一个 query string，但是实际上有[更强大的能力](https://github.com/webpack/loader-utils#parsequery):
query string -> 查询字符串(query string)

2020-06-25 06:02 UTC, lcxfs1991 commented on src/content/migrate/3.md
> +        issuer: /filename/, // 果请求 "/path/filename.js" 则匹配 "/path/something.js"
如果

2020-06-30 05:59 UTC, QC-L commented on src/content/migrate/3.md
多余的空行请删掉

2020-06-30 06:00 UTC, miazhuce commented on src/content/migrate/3.md
> +T> 注意：webpack 从 1 到 2 的变化，比从 2 到 3 要少很多，所以版本迁移起来难度应该不大。如果你遇到了问题，请查看 [更新日志](https://github.com/webpack/webpack/releases) 以了解更多细节。
修改完成提交

2020-06-30 06:00 UTC, miazhuce commented on src/content/migrate/3.md
> +旧的 loader 配置被更强大的 rules 系统取代，后者允许配置 loader 以及其他更多选项。 为了兼容旧版，`module.loaders` 语法仍然有效，旧的属性名依然可以被解析。 新的命名约定更易于理解，并且是升级配置使用 `module.rules` 的好理由。
修改完成提交

2020-06-30 06:00 UTC, miazhuce commented on src/content/migrate/3.md
> +好问题。严格来说，有两种办法，都可以用来配置 webpack 的 loader 。典型的 `options` 被称为 `query`，是一个可以被添加到 loader 名之后的字符串。它比较像一个 query string，但是实际上有[更强大的能力](https://github.com/webpack/loader-utils#parsequery):
修改完成提交

2020-06-30 06:00 UTC, miazhuce commented on src/content/migrate/3.md
> +        issuer: /filename/, // 果请求 "/path/filename.js" 则匹配 "/path/something.js"
修改完成提交

2020-06-30 06:02 UTC, miazhuce commented on src/content/migrate/3.md
额 跟master分支的3.md的一样
![image](https://user-images.githubusercontent.com/36191859/86089163-4ca8f700-bada-11ea-8ded-0ecd8cf7d842.png)

2020-06-30 06:04 UTC, miazhuce commented on src/content/migrate/3.md
done

2020-06-30 06:53 UTC, QC-L commented on src/content/migrate/3.md
```suggestion
```

2020-06-30 06:54 UTC, QC-L commented on src/content/migrate/3.md
> +就像在 webpack 1 中，loader 可以链式调用，上一个 loader 的输出被作为输入传给下一个 loader。 使用 [rule.use](/configuration/module/#ruleuse) 配置选项，`use` 可以设置为一个 loader 数组。 在 webpack 1 中，loader 通常被用 `!` 连写。这一写法在 webpack 2 中只在使用旧的选项 `
```suggestion
就像在 webpack 1 中，loader 可以链式调用，上一个 loader 的输出被作为输入传给下一个 loader。
使用 [rule.use](/configuration/module/#ruleuse) 配置选项，`use` 可以设置为一个 loader 数组。
在 webpack 1 中，loader 通常被用 `!` 连写。这一写法在 webpack 2 中只在使用旧的选项 `module.loaders` 时才有效。
```

2020-06-30 06:55 UTC, QC-L approved these changes

2020-06-30 06:55 UTC, merged