translate src/content/api/cli.md into Chinese
webpack-china/webpack.js.org pull request #787
Opened 2020-06-27 15:18 UTC by Fonkie

_describe your changes..._

- [ ] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [ ] Make sure your PR complies with the [writer's guide][2].
- [ ] Review the diff carefully as sometimes this can reveal issues.
- [ ] Do not abandon your Pull Request: [Stale Pull Requests][3].
- __Remove these instructions from your PR as they are for your eyes only.__

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

2020-07-05 06:06 UTC, Xeonice requested changes

2020-07-05 06:06 UTC, Xeonice commented on src/content/api/cli.md
> +一个文件名或一组被命名的文件名，作为构建项目的入口起点。你可以传递多个入口（每个入口在启动时加载）。如果传递一个形式为 `<name> = <request>` 的键值对，则可以创建一个额外的入口起点。它将被映射到配置选项（configuration option）的 `entry` 属性。
一个文件名或一组被命名的文件名会被用作项目构建的入口。你可以传递多个入口（每个入口在启动时加载）。如果传递一个形式为 `<name> = <request>` 的键值对，则可以创建一个额外的入口起点。它将被映射到配置文件中的 `entry` 属性。

2020-07-05 06:06 UTC, Xeonice commented on src/content/api/cli.md
> +要保存的 bundled 文件的路径和文件名。它将映射到配置选项 `output.path` 和 `output.filename`。
打包后的文件将被存取的路径和文件名。它将映射到配置文件中的 `output.path` 和 `output.filename` 属性中。

2020-07-05 06:06 UTC, Xeonice commented on src/content/api/cli.md
> +打包源码，入口为 `index.js`，并且输出文件的路径为 `dist`，文件名为 `bundle.js`
这会打包你的源代码，并将入口设定为 `index.js`，且打包文件的输出路径为 `dist`，文件名为 `bundle.js`

2020-07-05 06:06 UTC, Xeonice commented on src/content/api/cli.md
> +在其他每个情况下，webpack 会打印一组统计信息，用于显示 bundle, chunk 和用时等详细信息。使用此选项，输出可以是 JSON 对象。此输出文件(response)可被 webpack 的[分析工具](https://webpack.github.com/analyse)，或 chrisbateman 的 [webpack 可视化工具](https://chrisbateman.
```suggestion
在其他每个情况下，webpack 会打印一组统计信息，用于显示 bundle, chunk 和用时等详细信息。使用此选项，输出可以是 JSON 对象。此输出文件(response)可被 webpack 的[分析工具](https://webpack.github.com/analyse)、chrisbateman 的 [webpack 可视化工具](https://chrisbateman.github.io/webpack-visualizer/)或 th0r 的 [webpack bundle 分析工具](https://github.com/webpack-contrib/webpack-bundle-analyzer)接收后进行分析。分析工具将接收 JSON 并以图形形式提供构建的所有细节。
```

2020-07-05 06:06 UTC, Xeonice commented on src/content/api/cli.md
> +这些配置可以用于设置 webpack [resolver](/configuration/resolve/) 时使用的别名（alias）和扩展名（extension）。
@QC-L 这里没想到很好的翻译方案

2020-07-09 01:26 UTC, QC-L commented on src/content/api/cli.md
> +一个文件名或一组被命名的文件名，作为构建项目的入口起点。你可以传递多个入口（每个入口在启动时加载）。如果传递一个形式为 `<name> = <request>` 的键值对，则可以创建一个额外的入口起点。它将被映射到配置选项（configuration option）的 `entry` 属性。
```suggestion
构建项目时入口可以配置一个或一组被命名过的文件名。你可以传递多个入口（每个入口在启动时加载）。如果传递一个形式为 `<name> = <request>` 的键值对，则可以创建一个额外的入口起点。它将被映射到配置选项（configuration option）的 `entry` 属性中。
```

2020-07-09 01:28 UTC, QC-L commented on src/content/api/cli.md
> +要保存的 bundled 文件的路径和文件名。它将映射到配置选项 `output.path` 和 `output.filename`。
```suggestion
用于存储 bundle 文件的路径和文件名。它将映射到配置选项 `output.path` 和 `output.filename`。
```

2020-07-09 01:35 UTC, QC-L commented on src/content/api/cli.md
> +打包源码，入口为 `index.js`，并且输出文件的路径为 `dist`，文件名为 `bundle.js`
```suggestion
这将对源码进行打包，其入口为 `index.js`，且 bundle 文件的输出路径为 `dist`，文件名为 `bundle.js`
```

2020-07-09 01:38 UTC, QC-L commented on src/content/api/cli.md
> +这些配置可以用于设置 webpack [resolver](/configuration/resolve/) 时使用的别名（alias）和扩展名（extension）。
```suggestion
这些配置可以用于在设置 webpack [resolver](/configuration/resolve/) 时使用的别名（alias）和扩展名（extension）。
```

2020-07-09 01:38 UTC, QC-L commented on src/content/api/cli.md
> +这些配置可以用于设置 webpack [resolver](/configuration/resolve/) 时使用的别名（alias）和扩展名（extension）。
译者理解的没问题

2020-07-09 01:44 UTC, QC-L commented on src/content/api/cli.md
> +当 webpack 配置对象[导出为一个函数](/configuration/configuration-types/#exporting-a-function)时，可以向其传入一个“环境对象（environment）”。
```suggestion
当 webpack 配置对象[导出为一个函数](/configuration/configuration-types/#exporting-a-function)时，可以向其传入一个 "环境对象（environment）"。
```

2020-07-09 01:46 UTC, QC-L requested changes
稍微改改~基本没啥问题

2020-07-11 05:18 UTC, Fonkie commented on src/content/api/cli.md
> +一个文件名或一组被命名的文件名，作为构建项目的入口起点。你可以传递多个入口（每个入口在启动时加载）。如果传递一个形式为 `<name> = <request>` 的键值对，则可以创建一个额外的入口起点。它将被映射到配置选项（configuration option）的 `entry` 属性。
已修改

2020-07-11 05:18 UTC, Fonkie commented on src/content/api/cli.md
> +要保存的 bundled 文件的路径和文件名。它将映射到配置选项 `output.path` 和 `output.filename`。
已修改

2020-07-11 05:18 UTC, Fonkie commented on src/content/api/cli.md
> +打包源码，入口为 `index.js`，并且输出文件的路径为 `dist`，文件名为 `bundle.js`
已修改

2020-07-11 05:19 UTC, Fonkie commented on src/content/api/cli.md
> +一个文件名或一组被命名的文件名，作为构建项目的入口起点。你可以传递多个入口（每个入口在启动时加载）。如果传递一个形式为 `<name> = <request>` 的键值对，则可以创建一个额外的入口起点。它将被映射到配置选项（configuration option）的 `entry` 属性。
已修改

2020-07-12 04:23 UTC, QC-L approved these changes

2020-07-12 04:23 UTC, merged