docs(cn): translate src/content/loaders/sass-loader.md
webpack-china/webpack.js.org pull request #788
Opened 2020-06-28 02:07 UTC by wangjq4214

翻译 sass-loader

2020-06-28 02:07 UTC, wangjq4214 commented
@QC-L

2020-07-07 01:13 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +`sass-loader` 需要预先安装 [Dart Sass](https://github.com/sass/dart-sass) 或 [Node Sass](https://github.com/sass/node-sass)（可以在这两个链接中找到更多的资料）。这可以控制所有依赖的版本， 并自由的选择使用的 Sass 实现。
```suggestion
`sass-loader` 需要预先安装 [Dart Sass](https://github.com/sass/dart-sass) 或 [Node Sass](https://github.com/sass/node-sass)（可以在这两个链接中找到更多的资料）。
这可以控制所有依赖的版本，并自由的选择使用 Sass 的实现。
```

2020-07-07 01:16 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +### 解析 `import` at-rules
```suggestion
### 解析 `import` 的规则
```

2020-07-07 01:17 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +###  `url(...)` 的问题
```suggestion
### `url(...)` 的问题
```

2020-07-07 01:17 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +由于 Saass 的实现没有提供 [url rewriting](https://github.com/sass/libsass/issues/532) 的功能，所以相关的资源都必须是相对于输出文件（ouput）而言的。
```suggestion
由于 Saass 的实现没有提供 [url 重写](https://github.com/sass/libsass/issues/532)的功能，所以相关的资源都必须是相对于输出文件（ouput）而言的。
```

2020-07-07 01:19 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +例如此时 `sass-loader` 将会使用 `sass` （`dart-sass`）实现：
```suggestion
例如，此时 `sass-loader` 将会使用 `sass` （`dart-sass`）实现：
```

2020-07-07 01:20 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +例如此时 `sass-loader` 将会使用 `node-sass` 实现：
```suggestion
示例，此时 `sass-loader` 将会使用 `node-sass` 实现：
```

2020-07-07 01:20 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +需要注意同时安装 `node-sass` 和 `sass` 的情况！ 默认情况下，`sass-loader` 会选择 `sass`。
```suggestion
需注意同时安装 `node-sass` 和 `sass` 的情况！默认情况下，`sass-loader` 会选择 `sass`。
```

2020-07-07 01:23 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +> ℹ️ `indentedSyntax` 选项对于 `sass` 拓展为 `true`。
```suggestion
> ℹ️ `indentedSyntax` 选项值为 `true`，是对 `sass` 的扩展。
```

2020-07-07 01:25 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +> ℹ️ 像 `data` 和 `file` 这样的选项是不可用的并且他们将会被忽略。
```suggestion
> ℹ️ 像 `data` 和 `file` 这样的选项是不可用的，且会被忽略。
```

2020-07-07 01:28 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +开启 / 关闭生成 source maps。
```suggestion
开启/关闭生成 source map。
```

2020-07-07 01:29 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +在实际的文件之前要添加的 `Sass` / `SCSS` 代码。
```suggestion
在实际的文件之前要添加的 `Sass`/`SCSS` 代码。
```

2020-07-07 01:30 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +如果你要在 Chrome 中编辑原始的 Sass 文件， 建议阅读 [这篇不错的博客](https://medium.com/@toolmantim/getting-started-with-css-sourcemaps-and-in-browser-sass-editing-b4daab987fb0)。具体示例参考 [test/sourceMap](https://github.com/web
```suggestion
如果你要在 Chrome 中编辑原始的 Sass 文件，建议阅读 [这篇不错的博客](https://medium.com/@toolmantim/getting-started-with-css-sourcemaps-and-in-browser-sass-editing-b4daab987fb0)。具体示例参考 [test/sourceMap](https://github.com/webpack-contrib/sass-loader/tree/master/test)。
```

2020-07-07 01:31 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +开启 / 关闭 source maps 的生成。
```suggestion
开启/关闭 source map 的生成。
```

2020-07-07 01:31 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +  devtool: 'source-map', // 任何类似于“source-map”的选项都是可以的
```suggestion
  devtool: 'source-map', // 任何类似于 "source-map" 的选项都是可以的
```

2020-07-07 01:32 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +> ℹ 由于代码代码，将破坏入口文件的 source mappings。 通常一个简单的解决方案，多个 Sass 入口文件。
```suggestion
> ℹ 由于代码代码，将破坏入口文件的 source mappings。通常一个简单的解决方案，多个 Sass 入口文件。
```

2020-07-07 01:32 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +在某些情况下，可以提高性能。 但是请谨慎使用，因为 aliases 和以 `〜` 开头的 `@import` 规则将不起作用。
```suggestion
在某些情况下，可以提高性能。但是请谨慎使用，因为 aliases 和以 `〜` 开头的 `@import` 规则将不起作用。
```

2020-07-07 01:32 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +对于生产版本，我们建议从 bundle 中提取 CSS，以便之后可以使 CSS / JS 资源并行加载。
```suggestion
对于生产版本，我们建议从 bundle 中提取 CSS，以便之后可以使 CSS/JS 资源并行加载。
```

2020-07-07 01:33 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +从 bundle 中提取样式表，有2种可用的方法：
```suggestion
从 bundle 中提取样式表，有 2 种实用的方式：
```

2020-07-07 01:34 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +- Library 作者一般都会提供变量，用来设置资源路径。 比如 [bootstrap-sass](https://github.com/twbs/bootstrap-sass) 可以通过 `$icon-font-path` 进行设置。
```suggestion
- Library 作者一般都会提供变量，用来设置资源路径。比如 [bootstrap-sass](https://github.com/twbs/bootstrap-sass) 可以通过 `$icon-font-path` 进行设置。
```

2020-07-07 01:34 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +|     **[`prependData`](#sassoptions)**     | `{String\|Function}` |    `undefined`     | 在实际的输入文件之前添加 `Sass` /`SCSS` 代码。 |
```suggestion
|     **[`prependData`](#sassoptions)**     | `{String\|Function}` |    `undefined`     | 在实际的输入文件之前添加 `Sass`/`SCSS` 代码。 |
```

2020-07-07 01:35 UTC, QC-L commented on src/content/loaders/sass-loader.md
>  ## Contributing
```suggestion
## 贡献
```

2020-07-07 01:36 UTC, QC-L approved these changes

2020-07-07 01:56 UTC, QC-L commented on src/content/loaders/sass-loader.md
>  > ℹ️ Access to the [loader context](/api/loaders/#the-loader-context) inside the custom importer can be done using the `this.webpackLoaderContext` property.
这里是更新的内容，翻译一下

2020-07-07 01:56 UTC, QC-L commented on src/content/loaders/sass-loader.md
>  > ℹ️ We recommend using [Dart Sass](https://github.com/sass/dart-sass).
这里是更新的内容，需要翻译一下

2020-07-07 01:57 UTC, QC-L requested changes
新更新了一部分内容，翻译一下，没问题就可以合并了

2020-07-11 08:11 UTC, wangjq4214 commented
已经更新 @QC-L

2020-07-12 04:13 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +这样可以允许您控制所有依赖项的版本，并选择要使用的Sass实现。
```suggestion
这样可以控制所有依赖项的版本，并选择要使用的 Sass 实现。
```

2020-07-12 04:13 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +为了避免这种情况，您可以使用 `implementation` 选项。
```suggestion
为了避免这种情况，你可以使用 `implementation` 选项。
```

2020-07-12 04:13 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +如果可能，我们会自动注入 [`fibers`](https://github.com/laverdet/node-fibers) 软件包（设置 `sassOptions.fiber`）（当然需要您安装 [`fibers`](https://github.com/laverdet/node-fibers) 包）。
```suggestion
如果可能，我们会自动注入 [`fibers`](https://github.com/laverdet/node-fibers) 软件包（设置 `sassOptions.fiber`）（当然需要你安装 [`fibers`](https://github.com/laverdet/node-fibers) 包）。
```

2020-07-12 04:16 UTC, QC-L commented on src/content/loaders/sass-loader.md
> +> ℹ️ 可以使用 `this.webpackLoaderContext` 属性访问 custom  importer 中的 [loader context](/api/loaders/#the-loader-context)
```suggestion
> ℹ️ 可以使用 `this.webpackLoaderContext` 属性访问自定义 importer 中的 [loader 上下文](/api/loaders/#the-loader-context)
```

2020-07-12 04:18 UTC, QC-L approved these changes

2020-07-12 04:19 UTC, merged