docs(cn): translate src/content/plugins/dll-plugin.md
webpack-china/webpack.js.org pull request #795
Opened 2020-06-29 15:39 UTC by weiyuan0609

_describe your changes..._

- [ ] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [ ] Make sure your PR complies with the [writer's guide][2].
- [ ] Review the diff carefully as sometimes this can reveal issues.
- [ ] Do not abandon your Pull Request: [Stale Pull Requests][3].
- __Remove these instructions from your PR as they are for your eyes only.__

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

2020-07-07 10:55 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +这个插件是在一个额外的独立的 webpack 设置中创建一个只有 dll 的 bundle(dll-only-bundle)。 这个插件会生成一个名为 `manifest.json` 的文件，这个文件是用来让 [`DllReferencePlugin`](#dllreferenceplugin) 映射到相关的依赖上去的。
```suggestion
此插件用于在单独的 webpack 配置中创建一个 dll-only-bundle。此插件会生成一个名为 `manifest.json` 的文件，这个文件用于让 [`DllReferencePlugin`](#dllreferenceplugin) 能够映射到相应的依赖上。
```

2020-07-07 10:58 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +- `context` (可选的): manifest 文件中请求的上下文(context)(默认值为 webpack 的上下文(context))
```suggestion
- `context` (可选的)：manifest 文件中请求的 context（默认值为 webpack 的 context）
```

2020-07-07 10:59 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +- `format` (boolean = false): 如果为 `true`，则 manifest json 文件 (输出文件) 将被格式化。
```suggestion
- `format` (boolean = false)：如果为 `true`，则 manifest.json 文件 (输出文件) 将被格式化。
```

2020-07-07 10:59 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +- `path`: manifest json 文件的 __绝对路径__  (输出文件)
```suggestion
- `path`：manifest.json 文件的__绝对路径__（输出文件）
```

2020-07-07 11:00 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +- `name`: 暴露出的 DLL 的函数名 ([TemplatePaths](https://github.com/webpack/webpack/blob/master/lib/TemplatedPathPlugin.js): `[hash]` & `[name]` )
```suggestion
- `name`：暴露出的 DLL 的函数名（[TemplatePaths](https://github.com/webpack/webpack/blob/master/lib/TemplatedPathPlugin.js): `[hash]` & `[name]`）
```

2020-07-07 11:01 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +- `entryOnly` (boolean = true): 如果为 `true`，则仅暴露入口点
```suggestion
- `entryOnly` (boolean = true)：如果为 `true`，则仅暴露入口
```

2020-07-07 11:03 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +W> 我们建议仅将 DllPlugin 与 `entryOnly: true` 一起使用，否则 DLL 中的 tree shaking 将无法工作，因为可能会使用所有导出。
```suggestion
W> 我们建议 DllPlugin 只在 `entryOnly: true` 时使用，否则 DLL 中的 tree shaking 将无法工作，因为所有 exports 均可使用。
```

2020-07-07 11:05 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +在给定的 `path` 路径下创建一个名为 `manifest.json` 的文件。 这个文件包含了从 require 和 import 的 request 到模块 id 的映射。 `DllReferencePlugin` 也会用到这个文件。
```suggestion
在给定的 `path` 路径下创建一个 `manifest.json` 文件。这个文件包含了从 require 和 import 中 request 到模块 id 的映射。`DllReferencePlugin` 也会用到这个文件。
```

2020-07-07 11:06 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +这个插件与 [`output.library`](/configuration/output/#outputlibrary) 的选项相结合可以暴露出 (也称为放入全局作用域) dll 函数。
```suggestion
此插件与 [`output.library`](/configuration/output/#outputlibrary) 的选项相结合可以暴露出 (也称为放入全局作用域) dll 函数。
```

2020-07-07 11:08 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +这个插件是在 webpack 主配置文件中设置的， 这个插件把只有 dll 的 bundle(们)（dll-only-bundle(s)）引用到需要的预编译的依赖。
```suggestion
此插件配置在 webpack 的主配置文件中，此插件会把 dll-only-bundles 引用到需要的预编译的依赖中。
```

2020-07-07 11:08 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +_两个单独的用例，用来分别演示作用域(scope)和上下文(context)。_
```suggestion
_两个单独的用例，用来分别演示作用域（scope）和上下文（context）。_
```

2020-07-07 11:09 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +## 引用参考(References)
```suggestion
## 参考
```

2020-07-07 11:09 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +## 示例(Examples)
```suggestion
## 示例
```

2020-07-07 11:09 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +W> `DllReferencePlugin` 和 `DllPlugin` 都是在 _单独的_ webpack 设置中使用的。
```suggestion
W> `DllReferencePlugin` 和 `DllPlugin` 都是在_单独的_ webpack 配置中使用的。
```

2020-07-07 11:11 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +由于这是在解析了 dll 中每个文件之后才发生的，相同的路径必须能够确保这个 dll bundle 的使用者(不一定是人，可指某些代码)有权限访问。 举例来说， 假如一个 dll bundle 中含有 `loadash`库以及文件 `abc`， 那么 `require("lodash")` 和 `require("./abc")` 都不会被编译进主要的 bundle 文件，而是会被 dll 所使
```suggestion
由于这是在解析了 dll 中每个文件之后才触发的，因此相同的路径必须能够确保这个 dll bundle 的使用者（不一定是人，可指某些代码）有权限访问。举例来说，假如一个 dll bundle 中含有 `loadash` 库以及文件 `abc`，那么 `require("lodash")` 和 `require("./abc")` 都不会被编译进主 bundle 文件中，而是会被 dll 所使用。
```

2020-07-07 11:13 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +dll 中的内容被映射到了当前目录下。如果一个被 `require` 的文件符合 dll 中的某个文件(解析之后)，那么这个dll中的这个文件就会被使用。
```suggestion
dll 中的内容会被映射到当前目录下。如果被 `require` 的文件与 dll 中的某个文件匹配（解析之后），那么这个 dll 中的文件就会被使用。
```

2020-07-07 11:15 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +dll 中的内容可以在模块前缀下被引用，举例来说，令 `scope = 'xyz'` 的话，这个 dll 中的名为 `abc` 的文件可以通过 `require('xyz/abc')` 来获取。
```suggestion
dll 中的内容可以使用模块前缀的方式引用，举例来说，设置 `scope = 'xyz'`，这个 dll 中的名为 `abc` 的文件可以通过 `require('xyz/abc')` 来获取。
```

2020-07-07 11:15 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +这个插件支持两种模式，分别是作用域(_scoped_)和映射(_mapped_)。
```suggestion
这个插件支持两种模式，分别是作用域（_scoped_）和映射（_mapped_）。
```

2020-07-07 11:17 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +W> 与 [`output.library`](/configuration/output/#outputlibrary) 保持 `name` 的一致性。
```suggestion
W> 保持 `name` 与 [`output.library`](/configuration/output/#outputlibrary) 一致。
```

2020-07-07 11:17 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +通过引用 dll 的 manifest 文件来把依赖的名称映射到模块的 id 上，之后再在需要的时候通过内置的 `__webpack_require__` 函数来 `require` 他们
```suggestion
通过引用 dll 的 manifest 文件来把依赖的名称映射到模块的 id 上，之后再在需要的时候通过内置的 `__webpack_require__` 函数来 `require` 对应的模块
```

2020-07-07 11:21 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +- `context`: (__绝对路径__)  manifest (或者是内容属性)中请求的上下文
```suggestion
- `context`：（__绝对路径__） manifest (或者是内容属性)中的请求上下文
```

2020-07-07 11:21 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +- `extensions`: 用于解析 dll bundle 中模块的扩展名 (仅在使用 'scope' 时使用)。
```suggestion
- `extensions`：用于解析 dll bundle 中模块的扩展名 (仅在使用 'scope' 时使用)。
```

2020-07-07 11:22 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +- `manifest` : 包含 `content` 和 `name` 的对象，或者在编译时(compilation)的一个用于加载的 JSON manifest 绝对路径
```suggestion
- `manifest`：包含 `content` 和 `name` 的对象，或者是一个字符串 —— 编译时用于加载 JSON manifest 的绝对路径
```

2020-07-07 11:23 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +- `content` (可选的):  请求到模块 id 的映射 (默认值为 `manifest.content`)
```suggestion
- `content`（可选的）：请求到模块 id 的映射（默认值为 `manifest.content`）
```

2020-07-07 11:24 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +- `name` (可选的): dll 暴露的地方的名称 (默认值为 `manifest.name`) (可参考[`externals`](/configuration/externals/))
```suggestion
- `name`（可选的）：dll 暴露地方的名称（默认值为 `manifest.name`）（可参考[`externals`](/configuration/externals/)）
```

2020-07-07 11:24 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +- `scope` (可选的): dll 中内容的前缀
```suggestion
- `scope` （可选）：dll 中内容的前缀
```

2020-07-07 11:24 UTC, QC-L commented on src/content/plugins/dll-plugin.md
> +- `sourceType` (可选的): dll 是如何暴露的 ([libraryTarget](/configuration/output/#outputlibrarytarget))
```suggestion
- `sourceType`（可选）：dll 是如何暴露的 ([libraryTarget](/configuration/output/#outputlibrarytarget))
```

2020-07-07 11:25 UTC, QC-L requested changes
问题蛮多的，修改下吧

2020-07-07 11:26 UTC, QC-L commented
读着并不顺畅

2020-07-08 07:18 UTC, weiyuan0609 commented
按照建议，做了调整 @QC-L

2020-07-08 07:18 UTC, weiyuan0609 commented
按照建议，做了调整 @QC-L

2020-07-08 10:03 UTC, QC-L approved these changes

2020-07-08 10:04 UTC, merged