docs(cn): translate src/content/loaders/thread-loader.md
webpack-china/webpack.js.org pull request #818
Opened 2020-07-20 14:39 UTC by weiyuan0609

_describe your changes..._

- [ ] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [ ] Make sure your PR complies with the [writer's guide][2].
- [ ] Review the diff carefully as sometimes this can reveal issues.
- [ ] Do not abandon your Pull Request: [Stale Pull Requests][3].
- __Remove these instructions from your PR as they are for your eyes only.__

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

2020-07-28 15:52 UTC, QC-L commented
需要合并下冲突~

2020-07-30 09:53 UTC, IFnGSiYu commented
中文官网文档没有和英文官网同步

2020-07-30 15:29 UTC, QC-L commented
> 中文官网文档没有和英文官网同步

你看的官网是假的，被百度欺骗了，我们的链接是 https://webpack.docschina.org

2020-07-31 00:52 UTC, IFnGSiYu commented
我看了一个星期的假网站！~ ！

2020-08-03 03:51 UTC, weiyuan0609 commented
冲突解决了

2020-08-03 06:11 UTC, QC-L commented
{#} 中的内容不需要翻译...

2020-08-03 12:15 UTC, weiyuan0609 commented
已改

2020-08-04 01:22 UTC, QC-L commented on src/content/loaders/thread-loader.md
> +把此 loader 放置在其他 loader 之前， 放置在此 loader 之后的 loader 就会在一个单独的 worker 池中运行。
```suggestion
使用时，需将此 loader 放置在其他 loader 之前。放置在此 loader 之后的 loader 会在一个独立的 worker 池中运行。
```

2020-08-04 01:37 UTC, QC-L commented on src/content/loaders/thread-loader.md
> +* 这些 loader 不能产生新的文件。
```suggestion
* 这些 loader 不能生成新的文件。
```

2020-08-04 01:38 UTC, QC-L commented on src/content/loaders/thread-loader.md
> +* 这些 loader 不能使用定制的 loader API（也就是说，通过插件）。
```suggestion
* 这些 loader 不能使用自定义的 loader API（也就是说，通过插件的形式）。
```

2020-08-04 02:05 UTC, QC-L commented on src/content/loaders/thread-loader.md
> +* 这些 loader 无法获取 webpack 的选项设置。
```suggestion
* 这些 loader 无法获取 webpack 的配置。
```

2020-08-04 02:08 UTC, QC-L commented on src/content/loaders/thread-loader.md
> +每个 worker 都是一个单独的有 600ms 限制的 node.js 进程。同时跨进程的数据交换也会被限制。
```suggestion
每个 worker 都是一个独立的 node.js 进程，其开销大约为 600ms 左右。同时会限制跨进程的数据交换。
```

2020-08-04 02:09 UTC, QC-L commented on src/content/loaders/thread-loader.md
> +请仅在耗时的 loader 上使用!
```suggestion
请仅在耗时的操作中使用此 loader！
```

2020-08-04 02:12 UTC, QC-L commented on src/content/loaders/thread-loader.md
> +这会启动池内最大数量的 worker 并把指定的模块载入 node.js 的模块缓存中。
```suggestion
这会启动池内最大数量的 worker 并把指定的模块加载到 node.js 的模块缓存中。
```

2020-08-04 02:12 UTC, QC-L requested changes
看一下吧？感觉理解的有些问题。。。

2020-08-04 14:43 UTC, weiyuan0609 commented
语句翻译上确实不太流畅，已改

2020-08-05 11:12 UTC, QC-L commented on src/content/loaders/thread-loader.md
> +* 这些 loader 不能使用自定义的 loader API（也就是说，通过插件来自定义）。
```suggestion
* 这些 loader 不能使用自定义的 loader API（也就是说，不能通过插件来自定义）。
```

2020-08-05 11:14 UTC, QC-L approved these changes
感谢

2020-08-05 11:15 UTC, merged