docs(cn): translate src/content/loaders/css-loader.md
webpack-china/webpack.js.org pull request #829
Opened 2020-08-03 16:49 UTC by Jacksonlike

docs(cn): translate src/content/loaders/css-loader.md 
@QC-L

2020-08-04 13:02 UTC, QC-L commented on src/content/loaders/css-loader.md
> +`css-loader` 解释 `@import` 和 `url()` 就像是`import/require()` 一样，然后再解析它们。
```suggestion
`css-loader` 会 `@import` 和 `url()`，就 js 解析 `import/require()` 一样，然后再对它们进行处理。
```

2020-08-04 13:02 UTC, QC-L commented on src/content/loaders/css-loader.md
> +## 使用方法 {#getting-started}
```suggestion
## 快速开始 {#getting-started}
```

2020-08-04 13:02 UTC, QC-L commented on src/content/loaders/css-loader.md
> +一开始，你需要先安装 `css-loader`：
```suggestion
首先，你需要先安装 `css-loader`：
```

2020-08-04 13:03 UTC, QC-L commented on src/content/loaders/css-loader.md
> +然后通过你喜欢的方式运行 `webpack`。
```suggestion
然后运行 `webpack`。
```

2020-08-04 13:10 UTC, QC-L commented on src/content/loaders/css-loader.md
> +资源需要的好 loader 是你应该在配置文件中指定的 [file-loader](/loaders/file-loader/) 和 [url-loader](/loaders/url-loader/)([如下](https://github.com/webpack-contrib/css-loader#assets))。
```suggestion
[file-loader](/loaders/file-loader/) 和 [url-loader](/loaders/file-loader/) 能够非常好的处理资源文件，需在配置文件中进行配置，相关配置请[参阅](https://github.com/webpack-contrib/css-loader#assets)。
```

2020-08-04 13:12 UTC, QC-L commented on src/content/loaders/css-loader.md
> +例如，当你需要将 CSS 作为字符串进行后处理时，这很有用。
```suggestion
比如，当你需要对 CSS 进行后处理时，会非常有用。
```

2020-08-04 13:15 UTC, QC-L commented on src/content/loaders/css-loader.md
> +### 纯 CSS，CSS 模块和 PostCSS
```suggestion
### 纯 CSS，CSS 模块和 PostCSS {#pure-css-css-modules-and-postcss}
```

2020-08-04 13:17 UTC, QC-L commented on src/content/loaders/css-loader.md
>  ##### `exportlocalsConvention`
```suggestion
##### `exportlocalsConvention` {#exportlocalsconvention}
```

2020-08-04 13:18 UTC, QC-L commented on src/content/loaders/css-loader.md
>  ##### `exportOnlyLocals`
```suggestion
##### `exportOnlyLocals` {#exportonlylocals}
```

2020-08-04 13:18 UTC, QC-L commented on src/content/loaders/css-loader.md
> +### `sourceMap`
```suggestion
### `sourceMap` {#sourcemap}
```

2020-08-04 13:18 UTC, QC-L commented on src/content/loaders/css-loader.md
> +## 例子 {#examples}
```suggestion
## 示例 {#examples}
```

2020-08-04 13:20 UTC, QC-L commented on src/content/loaders/css-loader.md
> +如下 `webpack.config.js` 可以加载 CSS 文件，嵌入小的 PNG/JPG/GIF/SVG 图片以及字体作为[数据 URL](https://tools.ietf.org/html/rfc2397)，并将较大的文件复制到输出目录。
```suggestion
如下配置的 `webpack.config.js` 可以加载 CSS 文件，嵌入小的 PNG/JPG/GIF/SVG 图片以及字体作为[数据 URL](https://tools.ietf.org/html/rfc2397)，并将较大的文件复制到输出目录。
```

2020-08-04 13:22 UTC, QC-L commented on src/content/loaders/css-loader.md
> +在某些情况下，使用ES模块是有益的，例如在[模块串联](/plugins/module-concatenation-plugin/)和[tree shaking](/guides/tree-shaking/)。
```suggestion
在某些情况下，使用 ES 模块是有益的，例如在[模块串联](/plugins/module-concatenation-plugin/)或 [tree shaking](/guides/tree-shaking/) 时。
```

2020-08-04 13:23 UTC, QC-L commented on src/content/loaders/css-loader.md
> +默认：如果 `modules` 被启用则为 `true`，否则为 `false`
不需要换行，对齐

2020-08-04 13:26 UTC, QC-L requested changes
修改下

2020-08-04 15:07 UTC, Jacksonlike commented
> 修改下

已修复

2020-08-06 07:10 UTC, QC-L commented on src/content/loaders/css-loader.md
> +`css-loader` 会 `@import` 和 `url()`，就 js 解析 `import/require()` 一样，然后再对它们进行处理。
```suggestion
`css-loader` 会对 `@import` 和 `url()` 进行处理，就像 js 解析 `import/require()` 一样。
```

2020-08-08 06:41 UTC, QC-L commented
@Jacksonlike 周五又更新了一些东西，再合并下吧~这个文档变的比较频繁~

2020-08-12 02:53 UTC, QC-L approved these changes

2020-08-12 02:53 UTC, merged