docs(cn): translate src/content/plugins/split-chunks-plugins.md
webpack-china/webpack.js.org pull request #854
Opened 2020-09-24 13:18 UTC by weiyuan0609

_describe your changes..._

- [ ] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [ ] Make sure your PR complies with the [writer's guide][2].
- [ ] Review the diff carefully as sometimes this can reveal issues.
- [ ] Do not abandon your Pull Request: [Stale Pull Requests][3].
- __Remove these instructions from your PR as they are for your eyes only.__

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

2020-10-25 10:11 UTC, QC-L commented
开始看了~

2020-11-12 02:28 UTC, weiyuan0609 commented
> 开始看了~

👌

2020-11-16 02:03 UTC, weiyuan0609 commented
重新合并了

2021-02-15 01:59 UTC, jacob-lcs requested changes

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +- 新的 chunk 可以被多个 chunk 分享，或者它来自于 node_modules 文件夹
```suggestion
- 新的 chunk 可以被多个 chunk 分享，或者模块来自于 node_modules 文件夹
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +webpack 为希望对该功能进行更多控制的开发人员提供了一组选项。
```suggestion
webpack 为希望对该功能进行更多控制的开发者提供了一组选项。
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +W> 选择了默认配置以适合 Web 性能最佳实践，但是项目的最佳策略可能有所不同。如果要更改配置，则应评估所做更改的影响，以确保有真正的收益。
```suggestion
W> 选择默认配置是为了符合 web 性能最佳实践，但是项目的最佳策略可能有所不同。如果要更改配置，则应评估所做更改的影响，以确保有真正的收益。
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +W> 当 webpack 处理文件路径时，它们始终包含 `/` 在 Unix 系统和 `\` 在 Windows 上。这就是为什么 `[\\/]` 在 `{cacheGroup}.test` 字段中使用 in 来表示路径分隔符的原因。`/` 或 `\` in `{cacheGroup}.test` 会在跨平台使用时引起问题。
```suggestion
W> 当 webpack 处理文件路径时，它们始终包含Unix 系统中的 `/` 和 Windows 系统中的 `\`。这就是为什么在 `{cacheGroup}.test` 字段中使用 `[\\/]` 来表示路径分隔符。`{cacheGroup}.test` 中的 `/` 或 `\` 会在跨平台使用时引起问题。
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +W> 从 webpack 5 开始，不再允许将条目名称传递给 `{cacheGroup}.test` 现有的 chunk 并使用现有的 chunk 的名称 `{cacheGroup}.name`。
```suggestion
W> 从 webpack 5 开始，不再允许将 entry 名称传递给 `{cacheGroup}.test` 或者为 `{cacheGroup}.name` 使用现有的 chunk 的名称。
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +这表明将选择哪些 chunk 进行优化。当提供一个字符串，有效值为 `all`，`async` 和 `initial`。提供 `all` 可能特别强大，因为这意味着即使在异步和非异步 chunks 之间也可以共享 chunks。
```suggestion
这表明将选择哪些 chunk 进行优化。当提供一个字符串，有效值为 `all`、`async` 和 `initial`。提供 `all` 可能特别强大，因为这意味着 chunk 可以在异步和非异步 chunk 之间共享。
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +或者，您也可以提供一个函数去做更多的控制。这个函数的返回值将决定是否包含每一个 chunk。
```suggestion
或者，你也可以提供一个函数去做更多的控制。这个函数的返回值将决定是否包含每一个 chunk。
```

翻译中不要使用「**您**」这样的敬词

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +T> 您可以将此配置与 [HtmlWebpackPlugin](/plugins/html-webpack-plugin/) 结合使用。它将为您注入所有生成的 vendor chunks。
```suggestion
T> 您可以将此配置与 [HtmlWebpackPlugin](/plugins/html-webpack-plugin/) 结合使用。它将为你注入所有生成的 vendor chunks。
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +在 webpack 5中引入了 `splitChunks.minRemainingSize` 选项，通过确保拆分后剩余的最小 chunk 体积超过限制来避免大小为零的模块。 默认为 ['development' mode](/configuration/mode/#mode-development) 中的 `0`。对于其他情况，`splitChunks.minRemainingSize` 默认为
```suggestion
在 webpack 5 中引入了 `splitChunks.minRemainingSize` 选项，通过确保拆分后剩余的最小 chunk 体积超过限制来避免大小为零的模块。 ['development' 模式](/configuration/mode/#mode-development) 中默认为  `0`。对于其他情况，`splitChunks.minRemainingSize` 默认为 `splitChunks.minSize` 的值，因此除需要深度控制的极少数情况外，不需要手动指定它。
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +该算法是确定性的，对模块的更改只会产生局部影响。 这样，在使用长期缓存时就可以使用它并且不需要记录。 `maxSize` 只是一个提示，当模块大于 `maxSize` 时可能会被违反，否则拆分会违反 `minSize`。
```suggestion
该算法是确定性的，对模块的更改只会产生局部影响。 这样，在使用长期缓存时就可以使用它并且不需要记录。 `maxSize` 只是一个提示，当模块大于 `maxSize` 或者拆分不符合 `minSize` 时可能会被违反。
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +T> `maxSize` 比 `maxInitialRequest/maxAsyncRequests` 具有更高的优先级。实际优先级是 `maxInitialRequest/ maxAsyncRequests < maxSize < minSize`。
```suggestion
T> `maxSize` 比 `maxInitialRequest/maxAsyncRequests` 具有更高的优先级。实际优先级是 `maxInitialRequest/maxAsyncRequests < maxSize < minSize`。
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +像 `maxSize` 一样，`maxAsyncSize` 可以全局应用（`splitChunks.maxAsyncSize`），cacheGroups（`splitChunks.cacheGroups.{cacheGroup}.maxAsyncSize`）或后备缓存组（`splitChunks.fallbackCacheGroup.maxAsyncSize` ）。
```suggestion
像 `maxSize` 一样，`maxAsyncSize` 可以为 cacheGroups（`splitChunks.cacheGroups.{cacheGroup}.maxAsyncSize`）或 fallback 缓存组（`splitChunks.fallbackCacheGroup.maxAsyncSize` ）全局应用（`splitChunks.maxAsyncSize`）。
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +`maxAsyncSize` 和 `maxSize` 的区别在于 `maxAsyncSize` 仅会影响按需加载 chunks。
```suggestion
`maxAsyncSize` 和 `maxSize` 的区别在于 `maxAsyncSize` 仅会影响按需加载 chunk。
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +像 `maxSize` 一样，`maxInitialSize` 可以全局应用（splitChunks.maxInitialSize），cacheGroups（`splitChunks.cacheGroups.{cacheGroup}.maxInitialSize`）或后备缓存组（`splitChunks.fallbackCacheGroup.maxInitialSize`）。
```suggestion
像 `maxSize` 一样，`maxInitialSize` 可以对 cacheGroups（`splitChunks.cacheGroups.{cacheGroup}.maxInitialSize`）或 fallback 缓存组（`splitChunks.fallbackCacheGroup.maxInitialSize`）全局应用（splitChunks.maxInitialSize）。
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +每个 cacheGroup 也可以使用： `splitChunks.cacheGroups.{cacheGroup}.name`。
```suggestion
每个 cacheGroup 也可以使用：`splitChunks.cacheGroups.{cacheGroup}.name`。
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +拆分 chunk 的名称。 提供 `false` 将保持 chunk 的相同名称，因此不会不必要地更改名称。这是生产构建的建议值。
```suggestion
拆分 chunk 的名称。设为 `false` 将保持 chunk 的相同名称，因此不会不必要地更改名称。这是生产环境下构建的建议值。
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +T> 这将导致将  `react`和 `react-dom` 分成一个单独的 chunk。 如果您不确定 chunk 中包含哪些 packages，请参考 [Bundle Analysis](/guides/code-splitting/#bundle-analysis) 部分以获取详细信息。
```suggestion
T> 这将导致将 `react` 和 `react-dom` 分成一个单独的 chunk。 如果您不确定 chunk 中包含哪些包，请参考 [Bundle Analysis](/guides/code-splitting/#bundle-analysis) 部分以获取详细信息。
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> + 创建一个 `custom vendor` chunk，其中包含与 `RegExp` 匹配的某些 `node_modules` packages。
```suggestion
 创建一个 `custom vendor` chunk，其中包含与 `RegExp` 匹配的某些 `node_modules` 包。
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +创建一个 `vendors` chunk，其中包括整个应用程序中 `node_modules` 中的所有代码。
```suggestion
创建一个 `vendors` chunk，其中包括整个应用程序中 `node_modules` 的所有代码。
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +创建一个 `commons` chunk，其中包括 entry points 之间共享的所有代码。
```suggestion
创建一个 `commons` chunk，其中包括入口（entry points）之间所有共享的代码。
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +将 `helpers` 的内容放入每个 chunk 中将导致其代码被下载两次。通过使用单独的块，这只会发生一次。我们会支付额外请求的费用，这可以视为一种折衷。这就是为什么最小体积为 30kb 的原因。
```suggestion
将 `helpers` 的内容放入每个 chunk 中将导致其代码被下载两次。通过使用单独的块，这只会发生一次。我们会进行额外的请求，这可以视为一种折衷。这就是为什么最小体积为 30kb 的原因。
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +为什么？
```suggestion
为什么：
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +这背后的原因是什么？`react` 可能不会像您的应用程序代码那样频繁地更改。通过将其移动到单独的 chunk 中，可以将该 chunk 与应用程序代码分开进行缓存（假设您使用的是 chunkhash，records，Cache-Control 或其他长期缓存方法）。
```suggestion
这背后的原因是什么？`react` 可能不会像你的应用程序代码那样频繁地更改。通过将其移动到单独的 chunk 中，可以将该 chunk 与应用程序代码分开进行缓存（假设你使用的是 chunkhash，records，Cache-Control 或其他长期缓存方法）。
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +为什么？
```suggestion
为什么：
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +告诉 webpack 忽略 [`splitChunks.minSize`](#splitchunksminsize)，[`splitChunks.minChunks`](#splitchunksminchunks)，[`splitChunks.maxAsyncRequests`](#splitchunksmaxasyncrequests) 和 [`splitChunks.maxInitialRe
```suggestion
告诉 webpack 忽略 [`splitChunks.minSize`](#splitchunksminsize)、[`splitChunks.minChunks`](#splitchunksminchunks)、[`splitChunks.maxAsyncRequests`](#splitchunksmaxasyncrequests) 和 [`splitChunks.maxInitialRequests`](#splitchunksmaxinitialrequests) 选项，并始终为此缓存组创建 chunk。
```

2021-02-15 01:59 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +缓存组可以继承和 / 或覆盖来自 `splitChunks。*` 的任何选项。但是 `test`，`priority` 和 `reuseExistingChunk` 只能在缓存组级别上进行配置。要禁用任何默认缓存组，请将它们设置为 `false`。
```suggestion
缓存组可以继承和/或覆盖来自 `splitChunks.*` 的任何选项。但是 `test`、`priority` 和 `reuseExistingChunk` 只能在缓存组级别上进行配置。将它们设置为 `false`以禁用任何默认缓存组。
```

2021-02-15 02:00 UTC, jacob-lcs commented
麻烦尽快进行修改，翻译之后可以自己读一下看看是否有不合适的地方 @weiyuan0609

2021-02-20 06:57 UTC, weiyuan0609 commented
已调整

2021-02-20 09:55 UTC, jacob-lcs requested changes
请检查下全文，翻译中不要出现「您」这样的敬词

2021-02-20 09:55 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +最初，chunks（以及内部导入的模块）是通过内部 webpack 图谱中的父子关系关联的。`CommonsChunkPlugin` 曾被用来避免他们之间的重复依赖，但是进一步的优化是不可能的。
```suggestion
最初，chunks（以及内部导入的模块）是通过内部 webpack 图谱中的父子关系关联的。`CommonsChunkPlugin` 曾被用来避免他们之间的重复依赖，但是不可能再做进一步的优化。
```

2021-02-20 09:55 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
这里多了一行，要保持行行对应哈

2021-02-27 06:33 UTC, jacob-lcs requested changes

2021-02-27 06:33 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +对于大部分用户来说，`SplitChunksPlugin` 是开箱即用的，而且很适用。
```suggestion
开箱即用的 `SplitChunksPlugin` 对于大部分用户来说很好用。
```

2021-02-27 06:33 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +- 新的 chunk 可以被多个 chunk 分享，或者模块来自于 node_modules 文件夹
```suggestion
- 新的 chunk 可以被共享，或者模块来自于 `node_modules` 文件夹
```

2021-02-27 06:33 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +W> 当 webpack 处理文件路径时，它们始终包含 Unix 系统中的 `/` 和 Windows 系统中的 `\`。这就是为什么在 `{cacheGroup}.test` 字段中使用 `[\\/]` 来表示路径分隔符的原因。`{cacheGroup}.test` 中的 `/` 或 `\` 会在跨平台使用时引起问题。
```suggestion
W> 当 webpack 处理文件路径时，它们始终包含 Unix 系统中的 `/` 和 Windows 系统中的 `\`。这就是为什么在 `{cacheGroup}.test` 字段中使用 `[\\/]` 来表示路径分隔符的原因。`{cacheGroup}.test` 中的 `/` 或 `\` 会在跨平台使用时产生问题。
```

2021-02-27 06:33 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +默认情况下，webpack 将使用 chunk 的来源和名称生成名称（例如 `vendors~main.js`）。此选项使你可以指定用于生成名称的定界符。
```suggestion
默认情况下，webpack 将使用 chunk 的来源和名称生成名称（例如 `vendors~main.js`）。此选项使你可以指定用于生成名称的分隔符。
```

2021-02-27 06:33 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +这表明将选择哪些 chunk 进行优化。当提供一个字符串，有效值为 `all`，`async` 和 `initial`。提供 `all` 可能特别强大，因为这意味着 chunk 可以在异步和非异步 chunk 之间共享。
```suggestion
这表明将选择哪些 chunk 进行优化。当提供一个字符串，有效值为 `all`，`async` 和 `initial`。设置为 `all` 可能特别强大，因为这意味着 chunk 可以在异步和非异步 chunk 之间共享。
```

2021-02-27 06:33 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +拆分前必须共享模块的最小 chunks 数。
```suggestion
在拆分之前，module 在 chunk 之间共享的最少次数。
```

2021-02-27 06:33 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +为由 maxSize 分割的部分创建名称时，防止公开公共路劲信息。
```suggestion
为由 maxSize 分割的部分创建名称时，阻止公开路径信息。
```

2021-02-27 06:33 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +使用 `maxSize`（每个缓存组 `optimization.splitChunks.cacheGroups [x] .maxSize` 全局使用 `optimization.splitChunks.maxSize` 或对后备缓存组 `optimization.splitChunks.fallbackCacheGroup.maxSize` 使用）告诉 webpack 尝试尝试将大于 `max
```suggestion
使用 `maxSize`（每个缓存组 `optimization.splitChunks.cacheGroups[x].maxSize` 全局使用 `optimization.splitChunks.maxSize` 或对后备缓存组 `optimization.splitChunks.fallbackCacheGroup.maxSize` 使用）告诉 webpack 尝试将大于 `maxSize` 个字节的 chunk 分割成较小的部分。 这些较小的部分在体积上至少为 `minSize`（仅次于 `maxSize`）。
```

2021-02-27 06:33 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +该算法是确定性的，对模块的更改只会产生局部影响。 这样，在使用长期缓存时就可以使用它并且不需要记录。 `maxSize` 只是一个提示，当模块大于 `maxSize` 或者拆分不符合 `minSize` 时可能会被违反。
```suggestion
该算法是确定性的，对模块的更改只会产生局部影响。这样，在使用长期缓存时就可以使用它并且不需要记录。`maxSize` 只是一个提示，当模块大于 `maxSize` 或者拆分不符合 `minSize` 时可能会被违反。
```

2021-02-27 06:33 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +`maxSize` 选项旨在与 HTTP/2 和长期缓存一起使用。它增加了请求数量以实现更好的缓存。它还可以用于减小文件大小，以加快重建速度。
```suggestion
`maxSize` 选项旨在与 HTTP/2 和长期缓存一起使用。它增加了请求数量以实现更好的缓存。它还可以用于减小文件大小，以加快二次构建速度。
```

2021-02-27 06:33 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +使用以下 `splitChunks` 配置来运行 webpack 也会输出一组公用组，其下一个名称为：`commons-main-lodash.js.e7519d2bb8777058fa27.js`（以散列方式作为真实世界输出示例）。
```suggestion
使用以下 `splitChunks` 配置来运行 webpack 也会输出一组公用组，其下一个名称为：`commons-main-lodash.js.e7519d2bb8777058fa27.js`（以哈希方式作为真实世界输出示例）。
```

2021-02-27 06:33 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +一个模块可以属于多个缓存组。优化将优先考虑具有更高 `priority` 的缓存组 默认组的优先级为负，以允许自定义组获得更高的优先级（自定义组的默认值为 `0`）。
```suggestion
一个模块可以属于多个缓存组。优化将优先考虑具有更高 `priority`（优先级）的缓存组。默认组的优先级为负，以允许自定义组获得更高的优先级（自定义组的默认值为 `0`）。
```

2021-02-27 06:33 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +如果当前 chunk 包含已从主 bundle 中拆分出的模块，则它将被重用，而不是生成新的模块。 这可能会影响 chunk 的结果文件名。
```suggestion
如果当前 chunk 包含已从主 bundle 中拆分出的模块，则它将被重用，而不是生成新的模块。这可能会影响 chunk 的结果文件名。
```

2021-02-27 06:33 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +为 `{cacheGroup}.test` 提供一个功能：
```suggestion
为 `{cacheGroup}.test` 提供一个函数：
```

2021-02-27 06:33 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +__结果：__ 将创建一个单独的包含 `react` 的 chunk。在导入调用中，此 chunk 并行加载到包含 `./a` 的原始 chunk 中。
```suggestion
**结果：** 将创建一个单独的包含 `react` 的 chunk。在导入调用中，此 chunk 并行加载到包含 `./a` 的原始 chunk 中。
```

2021-02-27 06:33 UTC, jacob-lcs commented on src/content/plugins/split-chunks-plugin.md
> +__结果：__ 将创建一个单独的 chunk，其中包含 `./helpers` 及其所有依赖项。在导入调用时，此 chunk 与原始 chunks 并行加载。
```suggestion
**结果：** 将创建一个单独的 chunk，其中包含 `./helpers` 及其所有依赖项。在导入调用时，此 chunk 与原始 chunks 并行加载。
```

2021-03-02 08:18 UTC, weiyuan0609 commented
已调整

2021-03-03 01:20 UTC, QC-L commented on src/content/plugins/split-chunks-plugin.md
> +开箱即用的 `SplitChunksPlugin` 对于大部分用户来说很好用。
```suggestion
开箱即用的 `SplitChunksPlugin` 对于大部分用户来说非常友好。
```

2021-03-03 01:23 UTC, QC-L approved these changes

2021-03-03 01:24 UTC, merged