docs(cn): translate src/content/api/loaders.md
webpack-china/webpack.js.org pull request #951
Opened 2021-01-31 12:39 UTC by jacob-lcs

_describe your changes..._

- [x] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [x] Make sure your PR complies with the [writer's guide][2].
- [x] Review the diff carefully as sometimes this can reveal issues.
- [x] Do not abandon your Pull Request: [Stale Pull Requests][3].
- __Remove these instructions from your PR as they are for your eyes only.__

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

2021-01-31 12:41 UTC, jacob-lcs commented
因 #755 长时间未进行提交，故基于其翻译进行修改
@QC-L

2021-02-01 01:42 UTC, QC-L commented
收到~我马上看下

2021-02-01 01:54 UTC, QC-L commented on src/content/api/loaders.md
> +loader 是一个导出函数的 JavaScript 模块。[loader runner](https://github.com/webpack/loader-runner) 会调用这个函数，然后把上一个 loader 产生的结果或者资源文件传入进去。函数的 `this` 上下文将由 webpack 填充，并且 [loader runner](https://github.com/webpack
```suggestion
loader 本质上是导出为函数的 JavaScript 模块。[loader runner](https://github.com/webpack/loader-runner) 会调用此函数，然后将上一个 loader 产生的结果或者资源文件传入进去。函数中的 `this` 作为上下文会被 webpack 填充，并且 [loader runner](https://github.com/webpack/loader-runner) 中包含一些实用的方法，比如可以使 loader 调用方式变为异步，或者获取 query 参数。
```

2021-02-01 02:32 UTC, QC-L commented on src/content/api/loaders.md
> +第一个 loader 只有一个传入参数：资源文件的内容。compiler 预期得到最后一个 loader 产生的处理结果。这个处理结果应该是 `String` 或者 `Buffer`（能够被转换为 string），代表了模块的 JavaScript 源码。另外，还可以传递一个可选的 SourceMap 结果（格式为 JSON 对象）。
```suggestion
起始 loader 只有一个入参：资源文件的内容。compiler 预期得到最后一个 loader 产生的处理结果。这个处理结果应该为 `String` 或者 `Buffer`（能够被转换为 string）类型，代表了模块的 JavaScript 源码。另外，还可以传递一个可选的 SourceMap 结果（格式为 JSON 对象）。
```

2021-02-01 02:32 UTC, QC-L commented on src/content/api/loaders.md
> +如果是单个处理结果，可以在__同步模式__中直接返回。如果有多个处理结果，则必须调用 `this.callback()`。在__异步模式__中，必须调用 `this.async()` 来指示  [loader runner](https://github.com/webpack/loader-runner) 等待异步结果，它会返回 `this.callback()` 回调函数。随后 loader
```suggestion
如果是单个处理结果，可以在 __同步模式__ 中直接返回。如果有多个处理结果，则必须调用 `this.callback()`。在 __异步模式__ 中，必须调用 `this.async()` 来告知 [loader runner](https://github.com/webpack/loader-runner) 等待异步结果，它会返回 `this.callback()` 回调函数。随后 loader 必须返回 `undefined` 并且调用该回调函数。
```

2021-02-01 02:33 UTC, QC-L commented on src/content/api/loaders.md
> +如果是单个处理结果，可以在__同步模式__中直接返回。如果有多个处理结果，则必须调用 `this.callback()`。在__异步模式__中，必须调用 `this.async()` 来指示  [loader runner](https://github.com/webpack/loader-runner) 等待异步结果，它会返回 `this.callback()` 回调函数。随后 loader
要加个空格，不然 __ 无法解析

2021-02-01 02:34 UTC, QC-L commented on src/content/api/loaders.md
> +如果是单个处理结果，可以在__同步模式__中直接返回。如果有多个处理结果，则必须调用 `this.callback()`。在__异步模式__中，必须调用 `this.async()` 来指示  [loader runner](https://github.com/webpack/loader-runner) 等待异步结果，它会返回 `this.callback()` 回调函数。随后 loader
这块我过两天看看改下编译（英文间有空格，中文没有，就会有问题）

2021-02-01 02:35 UTC, QC-L commented on src/content/api/loaders.md
> +T> loader 最初被设计为可以在同步 loader pipelines（如 Node.js ，使用 [enhanced-require](https://github.com/webpack/enhanced-require))，_以及_在异步 pipelines（如 webpack ）中运行。然而在 Node.js 这样的单线程环境下进行耗时长的同步计算不是个好主意，我们建议尽可能地使你
```suggestion
T> loader 最初被设计为可以在同步 loader pipelines（如 Node.js ，使用 [enhanced-require](https://github.com/webpack/enhanced-require))，_以及_ 在异步 pipelines（如 webpack ）中运行。然而在 Node.js 这样的单线程环境下进行耗时长的同步计算不是个好主意，我们建议尽可能地使你的 loader 异步化。但如果计算量很小，同步 loader 也是可以的。
```

2021-02-01 02:39 UTC, QC-L commented on src/content/api/loaders.md
> +  // 即使不是 raw loader 也没问题
```suggestion
  // 即使不是 "raw"，loader 也没问题
```

2021-02-01 02:43 UTC, QC-L commented on src/content/api/loaders.md
> +loader __总是__从右到左被调用。有些情况下，loader 只关心 request 后面的__元数据(metadata)__，并且忽略前一个 loader 的结果。在实际（从右到左）执行 loader 之前，会先__从左到右__调用 loader 上的 `pitch` 方法。
```suggestion
loader __总是__ 从右到左被调用。有些情况下，loader 只关心 request 后面的 __元数据(metadata)__，并且忽略前一个 loader 的结果。在实际（从右到左）执行 loader 之前，会先 __从左到右__ 调用 loader 上的 `pitch` 方法。
```

2021-02-01 02:45 UTC, QC-L commented on src/content/api/loaders.md
> +T> loader 可以通过 request 添加或者禁用内联前缀，这将影响到 pitch 和 执行的顺序。更多详情查看 [`Rule.enforce`](/configuration/module/#ruleenforce)
```suggestion
T> loader 可以通过 request 添加或者禁用内联前缀，这将影响到 pitch 和执行的顺序。更多详情查看 [`Rule.enforce`](/configuration/module/#ruleenforce)
```

2021-02-01 02:45 UTC, QC-L commented on src/content/api/loaders.md
> +那么，为什么 loader 可以利用 "跳跃(pitching)" 阶段呢？
```suggestion
那么，为什么 loader 可以利用 "pitching" 阶段呢？
```

2021-02-01 02:46 UTC, QC-L commented on src/content/api/loaders.md
> +首先，传递给 `pitch` 方法的 `data`，在执行阶段也会暴露在 `this.data` 之下，并且可以用于在循环时，捕获和共享前面的信息。
```suggestion
首先，传递给 `pitch` 方法的 `data`，在执行阶段也会暴露在 `this.data` 之下，并且可以用于在循环时，捕获并共享前面的信息。
```

2021-02-01 02:47 UTC, QC-L commented on src/content/api/loaders.md
> +在我们的例子中：`"/abc/loader1.js?xyz!/abc/node_modules/loader2/index.js!/abc/resource.js?rrr"`
```suggestion
在我们的例子中：`'/abc/loader1.js?xyz!/abc/node_modules/loader2/index.js!/abc/resource.js?rrr'`
```

2021-02-01 02:49 UTC, QC-L commented on src/content/api/loaders.md
> +这个模块将获取像下面的 bundle
```suggestion
这个模块将获取像下面的 bundle：
```

2021-02-01 02:49 UTC, QC-L commented on src/content/api/loaders.md
> +T> 从 webpack 5 开始， `this.getOptions` 可以获取到 loader 上下文对象。 它用来替代来自 [loader-utils](https://github.com/webpack/loader-utils#getoptions) 中的 `getOptions` 方法。
```suggestion
T> 从 webpack 5 开始，`this.getOptions` 可以获取到 loader 上下文对象。 它用来替代来自 [loader-utils](https://github.com/webpack/loader-utils#getoptions) 中的 `getOptions` 方法。
```

2021-02-01 02:50 UTC, QC-L commented on src/content/api/loaders.md
> +一个可以同步或者异步调用的可以返回多个结果的函数。预期的参数是：
```suggestion
可以同步或者异步调用的并返回多个结果的函数。预期的参数是：
```

2021-02-01 02:52 UTC, QC-L commented on src/content/api/loaders.md
> +T> 请注意，如果 `stats.warnings` 设置为 `false`，警告信息将不会显示。 或者其他一些省略设置被用做 `status`, 例如 `none` 或者 `errors-only`。
```suggestion
T> 请注意，如果 `stats.warnings` 设置为 `false`，警告信息将不会显示。或者其他一些省略设置被用做 `status`, 例如 `none` 或者 `errors-only`。
```

2021-02-01 02:52 UTC, QC-L commented on src/content/api/loaders.md
> +T> 与抛出错误中断运行不同， 它不会中断当前模块的编译过程。
```suggestion
T> 与抛出错误中断运行不同，它不会中断当前模块的编译过程。
```

2021-02-01 02:53 UTC, QC-L commented on src/content/api/loaders.md
> +解析给定的 request 到一个模块，应用所有配置的 loader ，并且在回调函数中传入生成的 source 、sourceMap 和 模块实例（通常是 [`NormalModule`](https://github.com/webpack/webpack/blob/master/lib/NormalModule.js) 的一个实例）。如果你需要获取其他模块的源代码来生成结果的话，你可以使用
```suggestion
解析给定的 request 到模块，应用所有配置的 loader，并且在回调函数中传入生成的 source、sourceMap 和模块实例（通常是 [`NormalModule`](https://github.com/webpack/webpack/blob/master/lib/NormalModule.js) 的一个实例）。如果你需要获取其他模块的源代码来生成结果的话，你可以使用这个函数。
```

2021-02-01 02:54 UTC, QC-L commented on src/content/api/loaders.md
> +像 require 表达式一样解析一个 request 。
```suggestion
像 require 表达式一样解析一个 request。
```

2021-02-01 02:54 UTC, QC-L commented on src/content/api/loaders.md
> +- `request` 是要被解析的 request。 通常情况下，像 `./relative` 的相对请求或者像 `module/path` 的模块请求会被使用，但是像 `/some/path` 也有可能被当做 request。
```suggestion
- `request` 是要被解析的 request。通常情况下，像 `./relative` 的相对请求或者像 `module/path` 的模块请求会被使用，但是像 `/some/path` 也有可能被当做 request。
```

2021-02-01 02:55 UTC, QC-L commented on src/content/api/loaders.md
> +在 webpack [`resolve` options](/configuration/resolve/#resolve) 下的任意配置项都是可能的。他们会被合并进 `resolve` 配置项中。请注意，`"..."` 可以在数组中使用，用于拓展 `resolve` 配置项的值。例如：`{ extensions: [".sass", "..."] }`。
```suggestion
在 webpack [`resolve` 选项](/configuration/resolve/#resolve) 下的任意配置项都是可能的。他们会被合并进 `resolve` 配置项中。请注意，`"..."` 可以在数组中使用，用于拓展 `resolve` 配置项的值。例如：`{ extensions: [".sass", "..."] }`。
```

2021-02-01 02:56 UTC, QC-L commented on src/content/api/loaders.md
> +- 模块路径: `ERROR in ./src/lib.js`
```suggestion
- 模块路径：`ERROR in ./src/lib.js`
```

2021-02-01 02:56 UTC, QC-L commented on src/content/api/loaders.md
> +在webpack v4中引入了一种新的内联请求语法。前缀为 `<match-resource>!=!` 将为此请求设置  `matchResource`。
```suggestion
在 webpack v4 中引入了一种新的内联请求语法。前缀为 `<match-resource>!=!` 将为此请求设置  `matchResource`。
```

2021-02-01 02:58 UTC, QC-L commented on src/content/api/loaders.md
> +loader 可以将文件转换为以下文件，并使用 `matchResource` 应用用户指定的CSS处理规则：
```suggestion
loader 可以将文件转换为以下文件，并使用 `matchResource` 应用用户指定的 CSS 处理规则：
```

2021-02-01 02:59 UTC, QC-L requested changes
改一下吧，问题有点多

2021-02-03 02:04 UTC, QC-L approved these changes

2021-02-03 02:06 UTC, merged